/*
 Navicat Premium Data Transfer

 Source Server         : localhost_3306
 Source Server Type    : MySQL
 Source Server Version : 50721
 Source Host           : localhost:3306
 Source Schema         : sis

 Target Server Type    : MySQL
 Target Server Version : 50721
 File Encoding         : 65001

 Date: 07/06/2018 14:49:09
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for search_paper_title
-- ----------------------------
DROP TABLE IF EXISTS `search_paper_title`;
CREATE TABLE `search_paper_title`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `authors` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `publish_time` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `journal` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `authors_uniid` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1665 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of search_paper_title
-- ----------------------------
INSERT INTO `search_paper_title` VALUES (1001, '基于模拟退火的自适应水波优化算法', '王万良; 陈超; 李笠; 李伟琨', '2017', '计算机科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1002, '结合极大似然距离估计的MDS-MAP节点定位算法', '李津蓉; 王万良; 介婧; 姚信威', '2016', '传感技术学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1003, '基于实数编码量子进化算法的不规则多边形排样', '杨卫波; 王铮; 王万良; 张景玲', '2016', '计算机集成制造系统', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1004, '基于遗传模拟退火算法的矩形件优化排样', '杨卫波; 王万良; 张景玲; 赵燕伟', '2016', '计算机工程与应用', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1005, '电磁纳米网节能编码方法研究进展', '黄龙军; 王万良; 姚信威; 沈士根; 潘小刚', '2016', '电子学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1006, '面向节能和容错的异构WSNs数据收集算法', '杨明霞; 王万良; 马晨明', '2016', '传感技术学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1007, '无线传感器网络(k,m)-容错连通支配集的分布式构建', '马晨明; 王万良; 洪榛', '2016', '计算机科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1008, '基于决策树的HEVC编码单元划分算法', '岑跃峰; 王万良; 姚信威; 王超超; 潘铁强', '2016', '计算机科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1009, '一种基于反向CDS树的异构WSNs拓扑构建方法', '杨明霞; 王万良; 马晨明', '2016', '传感技术学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1010, '特征加权组稀疏判别投影分析算法', '郑建炜; 黄琼芳; 杨平; 王万良; 马文龙', '2016', '自动化学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1011, '有监督核化邻域投影分析算法', '郑建炜; 孔晨辰; 王万良; 邱虹; 章杭科', '2016', '计算机科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1012, '基于无线充电的Sink轨迹固定WSN路由算法', '徐新黎; 皇甫晓洁; 王万良; 吕琪', '2016', '仪器仪表学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1013, '梯级小水电群动态多目标优化调度', '王万良; 张羽方; 徐新黎; 李笠', '2016', '浙江工业大学学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1014, 'WSNs中基于隐马尔科夫模型的目标识别问题研究', '杨明霞; 王万良; 邵鹏飞', '2015', '计算机工程与应用', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1015, '基于时间序列的自适应采样机制策略研究', '杨明霞; 王万良; 邵鹏飞', '2015', '计算机科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1016, '基于生态惩罚的混联梯级小水电群优化调度', '周李智; 王万良; 徐新黎; 李笠; 郑舒天', '2015', '水力发电学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1017, '混联水库群分时电价下优化调度模型研究', '徐新黎; 杨丹; 王万良; 李笠', '2015', '浙江工业大学学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1018, '线性不动点近邻嵌入分析方法', '王万良', '2015', '模式识别与人工智能', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1019, '无线传感器网络中一种改进的能效数据收集协议', '马晨明; 王万良; 洪榛', '2015', '计算机科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1020, '一种自动巡检机器人无线接口通讯协议', '姚信威; 潘小刚; 王万良; 王超超; 李伟琨; 钟礼斌', '2015', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1021, '吞吐量最大化的二维无线能量传输算法', '姚信威; 郑星航; 王万良; 赵澄; 杨双华', '2015', '计算机科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1022, '一种基于媒介访问控制层驱动的网络时隙分配方法', '姚信威; 王超超; 王万良; 潘小刚; 钟礼斌; 郑星航; 赵燕伟', '2015', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1023, '太赫兹通信中MIMO信道建模与容量分析', '李伟琨; 姚信威; 王万良; 吴腾超', '2015', '计算机工程', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1024, '一种基于动态标签的RFID不确定性数据清洗算法', '王万良; 顾熙仁; 赵燕伟', '2014', '计算机科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1025, '一种基于QR分解的增量式核判别分析法', '王万良; 陈宇; 邱虹; 郑建炜', '2014', '计算机科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1026, 'HEVC快速编码深度选择算法', '王超超; 王万良; 岑跃峰; 姚信威; 姚晓敏', '2014', '计算机工程与应用', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1027, '基于拉氏搜索方向的DEE水电机组噪声异常检测方法', '郑建炜; 黄琼芳; 邱虹; 王万良; 王海伦', '2014', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1028, '视频传感器网络中基于移动目标轨迹预测的K级覆盖增强算法', '蒋一波; 陈琼; 王万良; 楼弘', '2014', '传感技术学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1029, '基于HLSNE的水轮机组状态监测实现方法', '郑建炜; 邱虹; 孔晨辰; 黄琼芳; 王万良', '2014', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1030, '基于快速判别公共向量算法的人体行为识别方法', '王万良; 邱虹; 黄凯; 韩珊珊; 郑建炜', '2014', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1031, '一种自适应二维无线能量传输方法', '王万良; 姚信威; 郑星航; 张羽方; 岑跃峰; 赵燕伟', '2014', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1032, '基于蚁群算法的带中间存储的流程工业生产调度研究', '赵澄; 王万良; 徐新黎', '2013', '高校化学工程学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1033, '面向QoS区分的自适应状态转移概率动态更新算法', '王万良; 陶砾; 姚信威; 岑跃峰', '2013', '', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1034, 'QoS区分的无线通信仿生建模', '王万良; 姚信威; 岑跃峰; 杨双华', '2013', '电子学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1035, '多目标差分进化算法求解柔性作业车间批量调度问题', '王万良; 范丽霞; 徐新黎; 赵燕伟; 张静', '2013', '计算机集成制造系统', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1036, '一种适于非线性过程在线监控的工业故障检测与诊断方法', '郑建炜; 邱虹; 陈宇; 蒋一波; 王万良; 金亦挺', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1037, '电话远程按键语音双模式控制器', '王万良; 姚信威; 张科娜; 陶砾; 韩姗姗; 赵燕伟; 陈盛勇', '2010', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1038, '基于快速SNE的人脸识别系统', '郑建炜; 黄琼芳; 王海伦; 邱虹; 王万良; 蒋一波', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1039, '高校党员管理系统', '王万良; 郑舒天; 陈晓倩; 杨丹; 徐新黎', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1040, '声纹识别系统', '郑建炜; 黄琼芳; 蒋一波; 章杭科; 王万良; 邱虹', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1041, '高校学习型党支部自评管理系统', '徐新黎; 郑舒天; 陈辰; 李笠; 王万良', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1042, '高校其他专业技术岗位网上报名系统', '徐新黎; 郑舒天; 陈辰; 周李智; 王万良', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1043, '水电站SCADA图形SVG编辑软件', '蒋一波; 陈琼; 楼弘; 王万良', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1044, '移动便民城市应用软件', '王万良; 郑舒天; 王楠; 王雨晨; 周盛伟; 陈辰', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1045, '一种基于局部保持非负矩阵分解的增量学习人脸识别方法', '郑建炜; 陈宇; 邱虹; 蒋一波; 王万良; 金亦挺', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1046, '基于核的判别随机近邻嵌入分析的人脸识别方法', '郑建炜; 黄琼芳; 邱虹; 王万良; 蒋一波', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1047, '基于重尾分布的KDSNE水电机组噪声源检测方法', '王万良; 邱虹; 郑建炜; 黄琼芳; 韩珊珊; 赵燕伟', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1048, '一种适于非线性过程在线监控的工业故障检测与诊断方法', '郑建炜; 邱虹; 陈宇; 蒋一波; 王万良; 金亦挺', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1049, '基于四叉树检索的配电网馈线遭台风破坏的风险评估方法', '蒋一波; 楼弘; 陈琼; 王万良', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1050, '基于云平台和AGPS的停车引导系统', '王万良; 岑跃峰; 姚信威; 吴腾超; 姚晓敏; 赵燕伟', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1051, '基于边缘相关性距离约束的角点匹配', '王万良; 金亦挺; 赵燕伟; 郑建炜', '2013', '计算机科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1052, '基于蜂窝的多角色交互性动画合成', '王鑫; 柳敏乾; 王万良', '2013', '计算机辅助设计与图形学学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1053, '增量式正交局部判别投影法', '郑建炜; 王万良; 蒋一波', '2013', '光电子-激光', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1054, '基于零空间分析的张量局部Fisher判别方法', '郑建炜; 蒋一波; 王万良', '2013', '计算机科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1055, '不同调制机制下无线传感网收发器能耗优化模型', '姚信威; 王万良; 吴腾超; 岑跃峰', '2013', '传感技术学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1056, '基于广义粗糙集的流程工业车间调度研究', '徐新黎; 施莉娜; 范丽霞; 王万良', '2012', '控制与决策', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1057, '点到弦距离累加的自适应角点检测', '王万良; 金亦挺; 赵燕伟; 胡峰俊', '2012', '中国图象图形学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1058, '一种IEEE 802.11网络的时隙分配方法', '王万良; 姚信威; 陶砾; 岑跃峰; 顾煕仁; 赵燕伟', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1059, '一种映射参数动态自适应的无线流媒体传输控制方法', '王万良; 姚信威; 韩姗姗; 李桂森; 张科娜', '2010', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1060, '基于家庭区域物联网的电话远程智能控制器', '王万良; 姚信威; 张科娜; 陶砾; 郑建炜; 韩姗姗; 蒋一波; 赵燕伟', '2010', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1061, '物流配送动态车辆调度平台', '赵燕伟; 张景玲; 李川; 任伟; 金亦挺; 王万良', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1062, '输电网模图编辑软件', '蒋一波; 郑建炜; 王雨晨; 王万良', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1063, '面向节能减排的印染生产调节系统', '徐新黎; 李笠; 张静; 王磊; 程徐; 王万良', '2013', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1064, '一种基于相似度的产品可拓分类知识挖掘方法', '赵燕伟; 洪欢欢; 王欢; 郭明; 王万良; 陈建; 姜高超', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1065, '一种配电网站外电气拓扑至潮流拓扑自动转换方法', '蒋一波; 郑建炜; 王万良', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1066, '一种利用鉴别随机邻域嵌入分析的数据降维方法', '郑建炜; 邱虹; 王万良; 蒋一波; 陈旻昊', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1067, '一种基于可拓传导效应的区域水能承载能力计算方法', '赵燕伟; 洪欢欢; 陆亿红; 王万良; 王欢; 姜高超; 张仁贡', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1068, '基于改进距的水资源能效可拓生态评价方法', '燕伟; 洪欢欢; 陆亿红; 王万良; 王欢; 毛亚明; 张仁贡', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1069, '一种基于双目视觉的鞋底喷胶厚度控制方法', '赵燕伟; 王万良; 胡峰俊; 金亦挺; 陈建', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1070, '一种小水电IED网中Zigbee协议与GOOSE协议的数据转换方法', '蒋一波; 陈琼; 郑建炜; 王雨晨; 王万良', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1071, '一种IEEE802.11网络的时隙分配方法', '王万良; 姚信威; 陶砾; 岑跃峰; 顾熙仁; 赵燕伟', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1072, '基于二次曲线拟合的旋转立体视觉旋转轴的确定方法', '陈胜勇; 刘大伟; 汪晓妍; 刘盛; 王万良', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1073, '创新性与满意度融合的用户创新方法及其在产品外观优化中的应用', '孙艳; 刘肖健; 王万良', '2012', '计算机辅助设计与图形学学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1074, '网络化智能控制与调度方法及其应用', '王万良; 赵燕伟; 徐新黎; 陆亿红; 郑建炜; 蒋一波; 张景玲; 姚信威; 岑跃峰', '2012', '中国人工智能学会', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1075, '小水电站网络化控制与优化运行关键共性技术及推广应用', '王万良; 裘江海; 徐锦才; 赵燕伟; 陆亿红; 姚岳来; 程夏蕾; 蒋一波; 陈烨兴; 董大富; 陈胜勇; 罗云霞; 陈晓健', '2012', '浙江省科技厅', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1076, '判别随机近邻嵌入分析方法', '郑建炜; 邱虹; 蒋一波; 王万良', '2012', '计算机辅助设计与图形学学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1077, '无线网络中基于流媒体传输的自适应TFRC机制', '王万良; 张小玮; 姚信威; 岑跃峰', '2012', '小型微型计算机系统', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1078, '张量局部Fisher判别分析的人脸识别', '郑建炜; 王万良; 姚晓敏; 石海燕', '2012', '自动化学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1079, 'Hybrid particle-swarm optimization for multi-objective flexible job-shop scheduling problem', '张静; 王万良; 徐新黎; 介婧', '2012', '控制理论与应用', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1080, 'Improved particle swarm algorithm for batch splitting flexible job shop scheduling', '张静; 王万良; 徐新黎; 王海燕', '2012', '控制与决策', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1081, 'Dynamic Job Shop scheduling based on hybrid differential evolution algorithm', '王万良; 王磊; 王海燕; 徐新黎; 赵燕伟', '2012', '计算机集成制造系统', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1082, 'User image oriented interactive genetic algorithm evaluation mode in product development', '孙艳; 王万良; 赵燕伟; 刘肖健', '2012', '计算机集成制造系统', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1083, 'New hybrid differential evolution for parallel machines batch scheduling', '王万良; 范丽霞; 徐新黎; 张静', '2012', '机电工程', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1084, '一种增量式类内局部保持降维算法', '王万良; 陈旻昊; 郑建炜; 黄琼芳', '2012', '计算机科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1085, '基于无线传感器网络的室内定位软件', '王万良; 姚信威; 王峥; 赵王军; 应皇城', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1086, '一种无线网络中改进的TCPW拥塞控制方法', '王万良; 刘琳琅; 岑跃峰; 蒋一波; 郑建炜; 赵燕伟', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1087, '一种基于网络编码的车载自组织网络区域内容分发方法', '王万良; 李桂森; 姚信威; 岑跃峰; 蒋一波; 赵燕伟', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1088, '一种无线局域网的语音质量测定方法', '王万良; 张科娜; 姚信威; 顾熙仁; 徐新黎; 赵燕伟', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1089, '一种IEEE 802.11网络的时隙分配方法', '王万良; 姚信威; 陶砾; 岑跃峰; 顾煕仁; 赵燕伟', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1090, '基于移动互联网的汽车远程控制与管理系统', '王万良; 岑跃峰; 姚信威; 李笠; 吴腾超; 赵燕伟', '2012', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1091, '车载自组网中基于滑动窗口的网络编码传输策略', '王万良; 李桂森; 姚信威; 岑跃峰', '2012', '计算机科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1092, 'Analysis Model of Voice Performance Based on IEEE802.11e Wireless Local Area Network', '张科娜; 王万良; 姚信威; 陶砾', '2012', '小型微型计算机系统', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1093, '视频传感器网络中无盲区覆盖优化算法', '蒋一波; 王万良; 陈伟杰; 郑建炜; 姚信威', '2012', '软件学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1094, '一种多信道无线mesh网络信道分配方法', '王万良; 姚信威; 张蛟; 陶砾; 岑跃峰; 赵燕伟', '2011', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1095, '海洋石油平台油气混输泵实时监控装置', '王万良,; 郑建炜; 蒋一波; 陈伟杰; 王震宇; 姚信威; 赵燕伟', '2009', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1096, '小水电站网络化控制与优化运行共性技术与装备', '王万良; 赵燕伟; 陆亿红; 蒋一波; 裘江海; 徐锦才; 姚岳来; 程夏蕾; 陈烨兴; 董大富', '2011', '中国机械工程学会', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1097, '高校产学研服务平台软件', '王万良; 濮约庆; 马庆; 桂元坤; 李川; 石海燕; 金亦挺', '2011', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1098, 'Pitch-Yaw结构的模块化机器人蜿蜒运动步态控制方法', '陈胜勇; 李秀丽; 方银峰; 汪晓研; 管秋; 王万良', '2011', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1099, '基于数据存储的电力系统短期负荷优化策略设计', '张仁贡; 王培萍; 王万良', '2011', '信息与控制', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1100, '基于保局部核RVM的说话人识别方法', '郑泽萍; 王万良; 郑建炜', '2011', '计算机工程', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1101, '基于运动传感器的手势识别', '王万良; 杨经纬; 蒋一波', '2011', '传感技术学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1102, '概率型稀疏核Logistic多元分类机', '郑建炜; 王万良; 蒋一波; 陈伟杰', '2011', '电子与信息学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1103, 'Ad Hoc网络中基于节点相关因子的多路径路由算法', '骆华强; 王万良; 姚信威', '2011', '计算机系统应用', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1104, '基于子块优化及全局整合的局部判别投影法', '郑建炜; 王万良; 姚信威', '2011', '电子与信息学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1105, '保局性数据域描述单类分类器', '郑建炜; 蒋一波; 王万良', '2011', '计算机科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1106, '基于无线网络的小区定位导航系统', '王万良; 陈青丽; 姚信威; 马庆', '2011', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1107, '基于遗传算法的Ogre路径搜索软件', '王万良; 俞凯杰; 陈秋迪; 濮约庆; 郑建炜; 马庆', '2011', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1108, '基于智能进化算法的无线传感器网络路由协议优化系统', '王万良; 姚信威; 岑跃峰; 赵燕伟; 石海燕', '2011', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1109, '无线传感网络智能分簇软件', '王万良; 姚信威; 岑跃峰; 赵燕伟', '2011', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1110, '障碍物遮挡环境下的视频传感器监视方向控制方法', '蒋一波; 郑建炜; 王万良; 姚信威', '2011', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1111, '一种多信道无线mesh网络信道分配方法', '王万良; 姚信威; 张蛟; 陶砾; 岑跃峰; 赵燕伟', '2011', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1112, 'Multiple Obstacles Adaptive Maximal Coverage Algorithm Based on Enhanced Virtual Force', '姚信威; 王万良; 岑跃峰; 蒋一波', '2011', '电信科学', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1113, 'Coverage Optimization of Occlusion-Free Surveillance for Video Sensor Networks', '蒋一波; 王万良; 陈伟杰; 郑建炜; 姚信威', '2011', '软件学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1114, 'NETWORK TRAFFIC PREDICTION MODEL BASED ON WAVELET TRANSFORM AND OPTIMISED SUPPORT VECTOR MACHINE', '周晓蕾; 王万良; 陈伟杰', '2011', '计算机应用与软件', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1115, 'Novel algorithm on semantic extraction of video key frame based on relevance vector machine', '吴昌; 王万良; 蒋一波', '2011', '计算机应用研究', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1116, 'Research on Hybrid Channel Assignment Algorithm in Wireless Mesh Network', '张蛟; 王万良; 姚信威; 陈伟杰', '2011', '计算机工程', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1117, 'HQEA-Based Energy-Efficient Routing Algorithm for WSN', '王翊; 范兴刚; 王万良; 姚晓敏', '2011', '传感技术学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1118, 'Intelligent Clustering Algorithm of WSN Based on DPSO', '范兴刚; 侯佳斌; 介靖; 王万良; 王翊', '2011', '传感技术学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1119, 'NFL:Adaptive fuzzy-logic-based AQM algorithm with active-flow parameter estimation', '陈伟杰; 王万良; 郑建炜; 蒋一波', '2011', '控制与决策', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1120, 'SABlue:A Self-tune AQM Algorithm with Acceleration Factor', '陈伟杰; 王万良; 蒋一波; 郑建炜', '2011', '电子与信息学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1121, 'Congestion awareness adaptive mapping mechanism oriented to remote video maintenance applications', '姚信威; 王万良; 陈伟杰; 赵燕伟', '2011', '计算机集成制造系统', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1122, '电话远程按键语音双模式控制器', '王万良; 姚信威; 张科娜; 陶砾; 韩姗姗; 赵燕伟; 陈胜勇', '2010', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1123, '基于家庭区域物联网的电话远程智能控制器', '王万良; 姚信威; 张科娜; 陶砾; 郑建炜; 韩姗姗; 蒋一波; 赵燕伟', '2010', '中国', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1124, 'DPSO-Based Multi-Layered Chain Routing Algorithm for WSN', '范兴刚; 王翊; 介婧; 王万良; 侯佳斌', '2010', '传感技术学报', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1125, '关于高校双语教学的探讨', '杨旭华; 蒋峰岭; 王万良', '2010', '中国校外教育', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1126, '面向视频维护的拥塞感知自适应映射方法及其应用', '姚信威; 王万良; 陈伟杰; 赵燕伟', '2010', '2010全国现代制造集成技术(CMIS)学术会议', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1127, '求解柔性作业车间调度问题的改进离散粒子群算法', '张静; 王万良; 徐新黎; 王海燕', '2010', '2010全国现代制造集成技术(CMIS)学术会议', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1128, '改进DE算法求解不确定流程车间调度问题', '王万良; 徐新黎; 施莉娜; 陈莉莉', '2010', '2010全国现代制造集成技术(CMIS)学术会议', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1129, 'Fuzzy flexible Job-shop scheduling method based on multi-agent immune algorithm', '徐新黎; 应时彦; 王万良', '2010', '控制与决策', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1130, '小波变换在妊娠超声图像的去噪中的应用研究', '毛本清; 王万良; 金小梅', '2010', '科技信息', 'UPQ2oUMJesA');
INSERT INTO `search_paper_title` VALUES (1131, 'EEXPSort-树形数据的高能效外存排序算法', '王靖; 周煜超; 龚卫华; 杨良怀', '2012', '计算机系统应用', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1132, '组合盘中结合访问次数与能量代价的文件缓存替换策略', '周健; 杨良怀; 龚卫华', '2012', '计算机系统应用', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1133, 'P2P环境下基于Vague集理论的主观信任模型研究', '黄德才; 翁挺; 龚卫华; 朱凌', '2011', '小型微型计算机系统', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1134, '基于主题的用户兴趣域算法', '龚卫华; 杨良怀; 金蓉; 丁维龙', '2011', '通信学报', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1135, '省精品课程数据库原理及应用教材建设', '黄德才; 陆亿红; 王松; 龚卫华; 熊丽荣', '2011', '计算机教育', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1136, '一种有效的异构盘高能效缓存机制', '窦少彬; 杨良怀; 龚卫华', '2011', '计算机系统应用', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1137, 'Schema Matching Research Progress: A Brief Survey', '潘超; 杨良怀; 龚卫华; 古辉; 陈敏智', '2010', '', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1138, 'kμ-Tree:a Space-efficient Index for Flash-based Embedded Databases', '黄志峰; 杨良怀; 龚卫华; 陈立军', '2010', '小型微型计算机系统', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1139, 'Survey of Queriable XML Data Compression Techniques', '童李文; 杨良怀; 龚卫华; 古辉', '2010', '计算机系统应用', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1140, 'Grid Task Dynamic Scheduling Algorithm Based on Connective-number', '黄德才; 龚卫华; 张丽君; 赵克勤', '2009', '计算机工程', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1141, '“数据库原理及应用”实验模块的组织原则与教学实践', '黄德才; 龚卫华', '2009', '计算机教育', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1142, 'RELATIONAL DATABASE WATERMARKING ALGORITHM BASED ON(t,n) THRESHOLD', '黄德才; 姚瑶; 刘端阳; 龚卫华', '2009', '计算机应用与软件', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1143, 'Strategy for Dynamic Data and Load Balancing in Heterogeneous Database Cluster', '龚卫华; 杨良怀; 黄德才', '2009', '小型微型计算机系统', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1144, 'Effective Hybrid Wear-leveling Algorithm for Flash Memory Management', '邢春波; 杨良怀; 龚卫华; 黄德才; 陈立军', '2009', '小型微型计算机系统', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1145, 'Quality measurement and scheduling algorithm of grid service based on evidence reasoning', '张丽君; 黄德才; 刘端阳; 龚卫华; 朱凌', '2008', '计算机集成制造系统', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1146, 'Improved Incremental Updating Algorithm for Association Rules', '黄德才; 张良燕; 龚卫华; 刘端阳', '2008', '计算机工程', 'JvUzHyT72BGInoTrNAOM3aQ');
INSERT INTO `search_paper_title` VALUES (1147, '基于3D人眼模型的视线跟踪技术综述', '周小龙; 汤帆扬; 管秋; 华敏', '2017', '计算机辅助设计与图形学学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1148, '基于颈动脉粥样硬化斑块的多序列MR图像去噪与配准', '李军伟; 汪晓妍; 张剑华; 何俊丽; 管秋; 陈胜勇', '2015', '中国图象图形学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1149, '上下文窄带约束下腹主动脉瘤外轮廓分割', '汪晓妍; 郑焕彰; 黄晓洁; 李军伟; 张剑华; 管秋; 陈胜勇', '2015', '浙江工业大学学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1150, '基于最优RANSAC算法的非增加式多视图三维重建', '管秋; 金俊杰; 张剑华; 李德明', '2015', '浙江工业大学学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1151, '基于结构显著性的医学图像质量评价', '张剑华; 张自然; 汪晓妍; 管秋', '2015', '浙江工业大学学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1152, '基于流形学习的人体动作识别', '王鑫; 沃波海; 管秋; 陈胜勇', '2014', '中国图象图形学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1153, 'Compounding Local Invariant Features and Global Deformable Geometry for Medical Image Registration', '张剑华; 陈磊; 汪晓妍; 腾忠照; Adam J. Brown; Jonathan H. Gillard; 管秋; 陈胜勇', '2014', 'PLos One', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1154, '基于流行学习的动作识别方法', '王鑫; 沃波海; 管秋; 陈胜勇', '2014', '中国图象图形学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1155, 'ISOGEOMETRIC ANALYSIS FOR DYNAMIC MODEL SIMULATION', '尹华斌; 管秋; 陈胜勇', '2011', '27st European Conference on Modelling and Simulation', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1156, '基于混合主动轮廓模型和区域间差别最大化的细胞弱边界分割', '赵明珠; 陈胜勇; 管秋', '2011', '计算机应用与软件', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1157, 'Heart modeling and parametric analysis from four-dimensional images', '陈胜勇; 管秋', '2011', '中国图象图形学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1158, 'Strain and Stress Analysis of Cardiac Ventricles from 4D Images', '管秋; 陈胜勇; 杜雅慧; 王万良', '2010', '计算机辅助设计与图形学学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1159, 'Robust reconstruction of high-resolution 3D shapes based on a single light pattern', '胡正周; 陈胜勇; 管秋; 刘盛; 李兰兰', '2010', '中国图象图形学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1160, '基于四维医学图像的心壁应力应变测量方法', '管秋; 杜雅慧等', '2009', '中国', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1161, '基于四维医学图像的应力应变计算', '杜雅慧; 管秋; 陈胜勇; 刘盛; 蒋超', '2009', '2009中国计算机大会', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1162, 'Active Detection and Correction of Shape Distortions Based on Moment Invariants for Active Shape Models', '张剑华; 陈胜勇; 刘盛; 管秋', '2009', '中国图象图形学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1163, 'Soft-sensing method development based on neural network for wastewater treatment', '管秋; 王万良; 徐新黎; 陈胜勇', '2006', '环境污染与防治', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1164, 'Design of a fuzzy PI controller with Smith predictor for networked control systems with long time delay', '陈惠英; 管秋; 王万良', '2005', '浙江工业大学学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1165, 'Research and practice of optimum operation method based on genetic algorithm for small hydropower stations', '王万良; 周慕逊; 管秋; 罗云霞; 徐新黎', '2005', '水力发电学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1166, 'A method of digital image watermarking based on wavelet and Fourier transform', '管秋; 唐浩; 徐新黎; 张聚; 王万良', '2005', '浙江工业大学学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1167, 'Digital Watermarking Based on Wavelet Transform with Random Sequence Scrambling', '王万良; 管秋; 杨旭东', '2004', '计算机辅助设计与图形学学报', 'gdC9pv0cs2BsWtCOpJd4RAg');
INSERT INTO `search_paper_title` VALUES (1168, '无线纳米网中太赫兹电磁波传输特性分析', '王万良; 吴腾超; 姚信威; 李伟琨; 陈超', '2015', '计算机科学', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1169, '无线纳米传感器网络最小化能耗编码方法', '黄龙军; 王万良; 姚信威', '2015', '电子学报', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1170, '带有能量补给的异构无线传感器网络拓扑控制算法', '马晨明; 王万良; 洪榛; 姚信威', '2015', '电信科学', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1171, '吞吐量最大化的二维无线能量传输算法', '姚信威; 郑星航; 王万良; 赵澄; 杨双华', '2015', '计算机科学', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1172, '多播网络中基于机会网络编码改进的重传方法', '邵鹏飞; 赵燕伟; 吴耀辉; 姚信威', '2015', '电信科学', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1173, '太赫兹通信中MIMO信道建模与容量分析', '李伟琨; 姚信威; 王万良; 吴腾超', '2015', '计算机工程', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1174, '一种自适应二维无线能量传输方法', '姚信威; 王万良; 郑星航; 张羽方; 岑跃峰; 赵燕伟', '2014', '浙江', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1175, 'QoS区分的无线通信仿生建模', '王万良; 姚信威; 岑跃峰; 杨双华', '2013', '电子学报', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1176, '无线网络中基于流媒体传输的自适应TFRC机制', '王万良; 张小玮; 姚信威; 岑跃峰', '2013', '', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1177, '面向QoS区分的自适应状态转移概率动态更新算法', '王万良; 陶砾; 姚信威; 岑跃峰', '2013', '', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1178, 'IEEE802.11e EDCA多优先级混合时隙传输方法', '王万良; 岑跃峰; 姚信威', '2013', '计算机科学', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1179, '不同调制机制下无线传感网收发器能耗优化模型', '姚信威; 王万良; 吴腾超; 岑跃峰', '2013', '传感技术学报', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1180, '基于云平台和AGPS的停车引导系统', '王万良; 岑跃峰; 姚信威; 吴腾超; 姚晓敏; 赵燕伟', '2013', '浙江', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1181, 'IEEE802.11e无线局域网语音性能分析模型', '张科娜; 王万良; 姚信威; 陶砾', '2012', '小型微型计算机系统', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1182, '车载自组网中基于滑动窗口的网络编码传输策略', '王万良; 李桂森; 姚信威; 岑跃峰', '2012', '计算机科学', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1183, 'GPID:变速PID主动队列管理算法', '刘琳琅; 王万良; 姚信威; 陈伟杰', '2012', '小型微型计算机系统', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1184, '视频传感器网络中无盲区监视优化', '蒋一波; 王万良; 陈伟杰; 郑建炜; 姚信威', '2012', '软件学报', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1185, '车载自组网中基于滑动窗口的网络编码传输策略', '王万良; 李桂森; 姚信威; 岑跃峰', '2012', '计算机科学', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1186, 'IEEE802.11e无线局域网语音性能分析模型', '张科娜; 王万良; 姚信威; 陶砾', '2012', '小型微型计算机系统', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1187, '视频传感器网络中无盲区监视优化', '蒋一波; 王万良; 陈伟杰; 郑建炜; 姚信威', '2012', '软件学报', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1188, '面向视频维护的拥塞感知自适应映射方法及其应用', '姚信威; 王万良; 陈伟杰; 赵燕伟', '2011', '计算机集成制造系统', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1189, 'Ad Hoc网络中基于节点相关因子的多路径路由算法', '骆华强; 王万良; 姚信威', '2011', '计算机系统应用', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1190, '基于增强虚拟力的自适应多障碍区域最大覆盖算法', '姚信威; 王万良; 岑跃峰; 蒋一波', '2011', '电信科学', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1191, '无线Mesh网络中混合信道分配算法研究', '张蛟; 王万良; 姚信威; 陈伟杰', '2011', '计算机工程', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1192, '基于子块优化及全局整合的局部判别投影法', '郑建炜; 王万良; 姚信威', '2011', '电子与信息学报', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1193, 'Ad Hoc网络中基于节点相关因子的多路径路由算法', '骆华强; 王万良; 姚信威', '2011', '计算机系统应用', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1194, '面向视频维护的拥塞感知自适应映射方法及其应用', '姚信威; 王万良; 陈伟杰; 赵燕伟', '2011', '计算机集成制造系统', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1195, '无线Mesh网络中混合信道分配算法研究', '张蛟; 王万良; 姚信威; 陈伟杰', '2011', '计算机工程', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1196, '基于子块优化及全局整合的局部判别投影法', '郑建炜; 王万良; 姚信威', '2011', '电子与信息学报', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1197, '基于增强虚拟力的自适应多障碍区域最大覆盖算法', '姚信威; 王万良; 岑跃峰; 蒋一波', '2011', '电信科学', 'BBd8X5gl31Oj2RJ6P1cipA');
INSERT INTO `search_paper_title` VALUES (1238, '有监督核化邻域投影分析算法', '郑建炜; 孔晨辰; 王万良; 邱虹; 章杭科', '2016', '计算机科学', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1239, '面向信息安全专业的立体信息化离散数学互动式教学方法设计', '赵明珠; 毛家发; 陈婉君; 郑建炜', '2016', '计算机教育', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1240, '组加权约束的核稀疏表示分类算法', '郑建炜; 杨平; 王万良; 白琮', '2016', '计算机研究与发展', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1241, '特征加权组稀疏判别投影分析算法', '郑建炜; 黄琼芳; 杨平; 王万良; 马文龙', '2016', '自动化学报', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1242, '视频传感器网络中多路径K级覆盖动态优化算法', '蒋一波; 陈琼; 王万良; 楼弘; 郑建炜', '2015', '仪器仪表学报', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1243, '视频传感器网络中基于双倍体遗传算法的多移动目标动态监测优化方法', '蒋一波; 盛尚浩; 楼弘; 郑建炜', '2014', '浙江', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1244, '线性不动点近邻嵌入分析方法', '邱虹; 王万良; 郑建炜', '2015', '模式识别与人工智能', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1245, '基于快速判别公共向量算法的人体行为识别方法', '王万良; 邱虹; 黄凯; 韩姗姗; 郑建炜', '2014', '浙江', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1246, '一种快速的判别公共向量分类方法', '韩姗姗; 黄凯; 王万良; 郑建炜; 蒋一波', '2014', '计算机科学', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1247, '基于HLSNE的水轮机组状态监测实现方法', '郑建炜; 邱虹; 孔晨辰; 黄琼芳; 王万良', '2014', '浙江', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1248, '一种基于QR分解的增量式核判别分析法', '王万良; 陈宇; 邱虹; 郑建炜', '2014', '计算机科学', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1249, '核判别随机近邻嵌入分析方法', '王万良; 邱虹; 黄琼芳; 郑建炜', '2014', '计算机辅助设计与图形学学报', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1250, '一种小水电IED网中Zigbee协议与GOOSE协议的数据转换方法', '蒋一波; 陈琼; 郑建炜; 王雨晨; 王万良', '2012', '浙江', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1251, '基于核的判别随机近邻嵌入分析的人脸识别方法', '郑建炜; 黄琼芳; 邱虹; 王万良; 蒋一波', '2013', '浙江', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1252, '面向终身教育的城市终身学习网的现状及改进', '郑建炜; 王海伦', '2013', '成人教育', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1253, '基于零空间分析的张量局部Fisher判别方法', '郑建炜; 蒋一波; 王万良', '2013', '计算机科学', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1254, '基于边缘相关性距离约束的角点匹配', '王万良; 金亦挺; 赵燕伟; 郑建炜', '2013', '计算机科学', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1255, '增量式正交局部判别投影法', '郑建炜; 王万良; 蒋一波', '2013', '光电子-激光', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1256, '网络化智能控制与调度方法及其应用', '王万良; 赵燕伟; 徐新黎; 陆亿红; 郑建炜; 蒋一波; 张景玲; 姚信威; 岑跃峰', '2012', '中国人工智能学会', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1257, '视频传感器网络中无盲区监视优化', '蒋一波; 王万良; 陈伟杰; 郑建炜; 姚信威', '2012', '软件学报', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1258, '判别随机近邻嵌入分析方法', '郑建炜; 邱虹; 蒋一波; 王万良', '2012', '计算机辅助设计与图形学学报', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1259, '张量局部Fisher判别分析的人脸识别', '郑建炜; 王万良; 姚晓敏; 石海燕', '2012', '自动化学报', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1260, '一种增量式类内局部保持降维算法', '王万良; 陈旻昊; 郑建炜; 黄琼芳', '2012', '计算机科学', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1261, '保局性数据域描述单类分类器', '郑建炜; 蒋一波; 王万良', '2011', '计算机科学', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1262, '密度诱导型数据描述单类分类机', '王万良; 王震宇; 郑建炜; 郑泽萍', '2011', '控制与决策', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1263, '基于子块优化及全局整合的局部判别投影法', '郑建炜; 王万良; 姚信威', '2011', '电子与信息学报', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1264, '概率型稀疏核Logistic多元分类机', '郑建炜; 王万良; 蒋一波; 陈伟杰', '2011', '电子与信息学报', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1265, '基于保局部核RVM的说话人识别方法', '郑泽萍; 王万良; 郑建炜', '2011', '计算机工程', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1266, 'NFL:一种基于活动流参数估计的自适应模糊AQM算法', '陈伟杰; 王万良; 郑建炜; 蒋一波', '2011', '控制与决策', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1267, 'SABlue:一种带加速因子的自适应AQM算法', '陈伟杰; 王万良; 蒋一波; 郑建炜', '2011', '电子与信息学报', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1268, '基于核方法的说话人辨认模型研究', '郑建炜', '2010', '计算机科学与技术学院', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1269, '一种输电网厂站节点可视化布局的渐进式自动生成方法', '蒋一波; 郑建炜; 王万良', '2010', '浙江', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1270, 'Speaker identification based on multi-class kernel Logistic regression model', '郑建炜; 王万良; 王震宇; 蒋一波', '2010', '控制与决策', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1271, 'Novel Local Within-class Features Preservation Kernel Fisher Discriminant Algorithm and Applied in Speaker Identification', '郑建炜; 王万良', '2010', '计算机科学', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1272, 'FINGERPRINT IMAGE ENHANCEMENT BASED ON WAVELET TRANSFORM AND TEAGER ENERGY OPERATOR', '王磊; 郑建炜; 王万良', '2010', '计算机应用与软件', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1273, 'Speaker Identification Approach of Hybrid GMM and RVM', '郑建炜; 王万良; 郑泽萍', '2010', '计算机工程', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1274, 'Fingerprint Minutiae Detection Based on Differential Code', '石旦旦; 王万良; 郑建炜; 刘健; 陈伟杰', '2010', '信息与控制', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1275, '基于Haar特征匹配的数字图像内容搜索方法', '蒋一波; 王万良; 郑建炜; 陈伟杰; 王翊', '2009', '浙江', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1276, '基于多元核logistic回归模型的说话人辨别实现方法', '王万良; 郑建炜; 郑泽萍; 韩姗姗; 蒋一波; 王震宇; 王磊; 陈胜勇', '2009', '浙江', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1277, 'Iterative re-constrained group sparse face recognition with adaptive weights learning', '郑建炜; 杨平; 陈胜勇; 沈国江; 王万良', '2011', 'IEEE Transactions on Image Processing', 'BBd8X5gl31NcqaL4AU1nhQ');
INSERT INTO `search_paper_title` VALUES (1278, '智能粒子群优化计算——控制方法、协同策略及优化应用', '介婧; 徐新黎', '2014', '科学出版社', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1279, '梯级小水电群动态多目标优化调度', '王万良; 张羽方; 徐新黎; 李笠', '2016', '浙江工业大学学报', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1280, '基于无线充电的Sink轨迹固定WSN路由算法', '徐新黎; 皇甫晓洁; 王万良; 吕琪', '2016', '仪器仪表学报', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1281, '基于生态惩罚的混联梯级小水电群优化调度', '周李智; 王万良; 徐新黎; 李笠; 郑舒天', '2015', '水力发电学报', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1282, '混联水库群分时电价下优化调度模型研究', '徐新黎; 杨丹; 王万良; 李笠', '2015', '浙江工业大学学报', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1283, '开放式教学法在物联网导论教学中的运用', '黄伟; 徐新黎', '2015', '计算机教育', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1284, '“自动控制原理”国家精品资源共享课程建设', '范兴刚; 徐新黎; 王万良', '2014', '电气电子教学学报', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1285, '基于蚁群算法的带中间存储的流程工业生产调度研究', '赵澄; 王万良; 徐新黎', '2013', '高校化学工程学报', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1286, '小水电生态径流计算数据预处理方法', '周李智; 王万良; 徐新黎; 赵燕伟', '2013', '小水电', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1287, '多目标差分进化算法求解柔性作业车间批量调度问题', '王万良; 范丽霞; 徐新黎; 赵燕伟; 张静', '2013', '计算机集成制造系统', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1288, '一种可改善整体换乘性能的城市公共交通网络优化方法', '杨旭华; 陈光; 蒋峰岭; 孙豹; 徐新黎; 富强; 张永振; 楼顺利', '2011', '', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1289, '多目标差分进化算法求解柔性作业车间批量调度问题', '王万良; 范丽霞; 徐新黎; 赵燕伟; 张静', '2013', '计算机集成制造系统', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1290, '网络化智能控制与调度方法及其应用', '王万良; 赵燕伟; 徐新黎; 陆亿红; 郑建炜; 蒋一波; 张景玲; 姚信威; 岑跃峰', '2012', '中国人工智能学会', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1291, '多Agent主从粒子群分布式计算框架', '郑宇军; 陈胜勇; 凌海风; 徐新黎', '2012', '软件学报', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1292, '基于广义粗糙集的流程工业车间调度研究', '徐新黎; 施莉娜; 范丽霞; 王万良', '2012', '控制与决策', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1293, '智能搜索算法在线教学实验平台的设计与实现', '徐新黎; 胡磊; 王万良; 杨旭华; 刘盛', '2012', '实验技术与管理', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1294, '基于组合拆分策略求解TSP的动态规划算法', '杨忠程; 徐新黎; 叶双挺', '2012', '计算机工程', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1295, '基于改进粒子群算法求解柔性作业车间批量调度问题', '张静; 王万良; 徐新黎; 王海燕', '2012', '控制与决策', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1296, '基于混合差分进化算法的作业车间动态调度', '王万良; 王磊; 王海燕; 徐新黎; 赵燕伟', '2012', '计算机集成制造系统', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1297, '混合粒子群算法求解多目标柔性作业车间调调度度问题', '张静; 王万良; 徐新黎; 介婧', '2012', '控制理论与应用', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1298, '基于多智能体的流程工业动态调度研究', '徐新黎; 俞靓亮; 王磊; 王万良', '2012', '计算机工程', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1299, '基于混合差分进化算法的并行机批处理调度问题研究', '王万良; 范丽霞; 徐新黎; 张静', '2012', '机电工程', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1300, '基于量子遗传算法的染缸排产问题研究', '蒋佳颖; 王万良; 徐新黎; 王海燕', '2011', '计算机工程', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1301, '复杂反应约束的流程优化调度问题及求解', '戴欣华; 王万良; 徐新黎', '2011', '计算机与应用化学', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1302, '改进差分进化算法求解不确定流程车间调度问题', '王万良; 徐新黎; 施莉娜; 陈莉莉', '2011', '计算机集成制造系统', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1303, '一种多产品多约束混合生产线的批量计划模型及其求解', '戴欣华; 王万良; 徐新黎', '2011', '计算机工程与科学', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1304, '面向电声零件行业的创新设计平台开发及企业应用系统研究', '应时彦; 王万良; 刘志斌; 牟永灿; 徐新黎; 郝平; 姜献锋; 裘晓彤; 彭国亮; 赵燕伟', '2010', '浙江省教育厅', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1305, '资源节约型生产过程控制与管理技术及其在印染行业组的应用', '郝平; 张聚; 应时彦; 徐新黎; 李章维; 王万良; 张泉; 郑国全', '2010', '浙江省教育厅', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1306, 'Fuzzy flexible Job-shop scheduling method based on multi-agent immune algorithm', '徐新黎; 应时彦; 王万良', '2010', '控制与决策', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1307, 'Research of ion exchange membranes shop scheduling problem based on improved PSO', '王万良; 周明; 徐新黎; 介婧', '2010', '控制与决策', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1308, 'New parallel algorithm based on DE for batch splitting job shop scheduling under multiple-resource constraints', '王海燕; 赵燕伟; 王万良; 徐新黎', '2010', '控制与决策', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1309, 'Multi-agent dynamic scheduling method and its application to dyeing shops scheduling', '徐新黎; 郝平; 王万良', '2010', '计算机集成制造系统', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1310, 'Design and Development of Intelligent Search Algorithm Teaching Software', '徐新黎; 金波; 陈胜勇; 管秋; 王万良', '2010', '计算机教育', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1311, 'Hybrid Differential Evolution Solving Job Shop Scheduling Problems', '周萧; 王万良; 徐新黎', '2010', '轻工机械', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1312, 'Research and Practice for Development of Postgraduate Innovation Ability', '陈胜勇; 姚春燕; 徐新黎; 王明环; 彭伟', '2010', '计算机教育', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1313, 'A Tentative Study in Teaching and Practice Reform of Introduction of Artificial Intelligence', '徐新黎; 王万良; 杨旭华', '2009', '计算机教育', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1314, 'Vat scheduling and dynamic optimal design based on genetic algorithm and multi-Agent', '郝平; 莫丰勇; 徐新黎', '2009', '计算机集成制造系统', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1315, 'Hybrid quantum inspired evolutionary algorithm for flow-shop scheduling problem', '王小芹; 王万良; 徐新黎', '2009', '机电工程', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1316, 'Scheduling batch and continuous process production based on an improved differential evolution algorithm', '王海燕; 赵燕伟; 徐新黎; 王万良', '2009', '系统工程理论与实践', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1317, 'Method to Resolve Flexible Job-shop Scheduling Problem Based on Improved Ant Colony Algorithm', '王万良; 赵澄; 熊婧; 徐新黎', '2008', '系统仿真学报', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1318, 'Research on Intelligent Production Scheduling Optimization Methods and Its Applications', '徐新黎', '2008', '控制理论与控制工程', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1319, '基于移动Agent的流媒体组播网实现方法及系统', '王万良; 蒋一波; 赵燕伟; 徐新黎; 任敏; 陈伟杰; 张美燕', '2007', '', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1320, '基于视频帧拆分的实时流媒体传输方法及系统', '王万良; 蒋一波; 赵燕伟; 任敏; 徐新黎; 郑建炜', '2006', '', 'thxMLiZ2TRbrUS24CammJQ');
INSERT INTO `search_paper_title` VALUES (1321, '一种基于受限玻尔兹曼机的路径点数据行为识别方法', '蒋一波', '2015', '中国', 'k2By2BHpfOQiUIJtkx0NfJ7Q');
INSERT INTO `search_paper_title` VALUES (1322, '视频传感器网络中多路径K级覆盖动态优化算法', '蒋一波; 陈琼; 王万良; 楼弘; 郑建炜', '2015', '仪器仪表学报', 'k2By2BHpfOQiUIJtkx0NfJ7Q');
INSERT INTO `search_paper_title` VALUES (1323, '一种基于贪心计算的视频传感器网络多移动目标监测优化方法', '蒋一波', '2014', '中国', 'k2By2BHpfOQiUIJtkx0NfJ7Q');
INSERT INTO `search_paper_title` VALUES (1324, '一种小水电IED网中Zigbee协议与GOOSE协议的数据转换方法', '蒋一波', '2012', '', 'k2By2BHpfOQiUIJtkx0NfJ7Q');
INSERT INTO `search_paper_title` VALUES (1325, '多分辨率协同遥感地块利用分类方法研究', '夏列钢', '2016', '地球信息科学学报', 'tXCtpUxTTKaDbmTIqtGccQ');
INSERT INTO `search_paper_title` VALUES (1326, '遥感信息图谱支持下影像自动解译方法研究', '夏列钢', '2014', '遥感与数字地球研究所', 'tXCtpUxTTKaDbmTIqtGccQ');
INSERT INTO `search_paper_title` VALUES (1327, '基于对象级分类的土地覆盖动态变化及趋势分析', '吴田军; 胡晓东; 夏列钢; 骆剑承; 沈占锋; 吴炜', '2014', '遥感技术与应用', 'tXCtpUxTTKaDbmTIqtGccQ');
INSERT INTO `search_paper_title` VALUES (1328, '遥感信息图谱支持的土地覆盖自动分类', '夏列钢; 骆剑承; 王卫红; 沈占锋', '2014', '遥感学报', 'tXCtpUxTTKaDbmTIqtGccQ');
INSERT INTO `search_paper_title` VALUES (1329, '迁移学习支持下的遥感影像对象级分类样本自动选择方法', '吴田军; 骆剑承; 夏列钢; 杨海平; 沈占锋; 胡晓东', '2014', '测绘学报', 'tXCtpUxTTKaDbmTIqtGccQ');
INSERT INTO `search_paper_title` VALUES (1330, '面向灾害应急土地覆被分类的样本自动选择方法研究', '温奇; 夏列钢; 李苓苓; 吴玮', '2013', '武汉大学学报(信息科学版)', 'tXCtpUxTTKaDbmTIqtGccQ');
INSERT INTO `search_paper_title` VALUES (1331, '复杂背景下多样水体遥感自动解译', '夏列钢; 沈占锋; 李均力; 骆剑承', '2013', '中国图象图形学报', 'tXCtpUxTTKaDbmTIqtGccQ');
INSERT INTO `search_paper_title` VALUES (1332, '应用湖泊中心点作为控制点实现大区域遥感影像的配准', '沈占锋; SHENG Yongwei; 骆剑承; 夏列钢', '2013', '遥感学报', 'tXCtpUxTTKaDbmTIqtGccQ');
INSERT INTO `search_paper_title` VALUES (1333, '基于Bhattacharyya距离的典型地物波谱特征差异性分析', '程熙; 沈占锋; 周亚男; 夏列钢; 骆剑承', '2013', '遥感技术与应用', 'tXCtpUxTTKaDbmTIqtGccQ');
INSERT INTO `search_paper_title` VALUES (1334, '面向多目标视频跟踪的出生强度估计方法', '周小龙; 沈恒华; 何炳蔚', '2014', '计算机辅助设计与图形学学报', '2FftEsr9oKfS2uPCVwVC6Dw');
INSERT INTO `search_paper_title` VALUES (1335, '融合SFS和主动视觉技术的未知物体重建方法', '何炳蔚; 陈志鹏; 林东艺; 周小龙', '2012', '仪器仪表学报', '2FftEsr9oKfS2uPCVwVC6Dw');
INSERT INTO `search_paper_title` VALUES (1336, '基于单目视觉可视空间的视点规划方法', '何炳蔚; 周小龙', '2010', '仪器仪表学报', '2FftEsr9oKfS2uPCVwVC6Dw');
INSERT INTO `search_paper_title` VALUES (1337, '线激光三维测量仪中视觉传感器规划方法研究', '何炳蔚; 周小龙', '2010', '中国激光', '2FftEsr9oKfS2uPCVwVC6Dw');
INSERT INTO `search_paper_title` VALUES (1338, '面向未知物体自动测量和重建的视点规划方法', '何炳蔚; 周小龙', '2010', '计算机辅助设计与图形学学报', '2FftEsr9oKfS2uPCVwVC6Dw');
INSERT INTO `search_paper_title` VALUES (1339, '基于可视空间的未知三维物体自动建模视点规划方法研究', '何炳蔚; 周小龙', '2009', '仪器仪表学报', '2FftEsr9oKfS2uPCVwVC6Dw');
INSERT INTO `search_paper_title` VALUES (1340, '面向未知三维物体自动建模的视点规划方法研究', '何炳蔚; 周小龙', '2008', '中国工程机械学报', '2FftEsr9oKfS2uPCVwVC6Dw');
INSERT INTO `search_paper_title` VALUES (1341, '基于3D人眼模型的视线跟踪技术综述', '周小龙; 汤帆扬; 管秋; 华敏', '2008', '计算机辅助设计与图形学学报', '2FftEsr9oKfS2uPCVwVC6Dw');
INSERT INTO `search_paper_title` VALUES (1342, '基于Petri网的流程元素映射方法', '曹斌; 王佳星; 范菁; 董天阳', '2015', '软件学报', '876A4OG7xU1HEKWgKfd4zQ');
INSERT INTO `search_paper_title` VALUES (1343, 'JTangWFR:一个高效可靠的流程推荐系统', '王东京; 邓水光; 曹斌; 尹建伟; 熊丽荣', '2013', '计算机集成制造系统', '876A4OG7xU1HEKWgKfd4zQ');
INSERT INTO `search_paper_title` VALUES (1344, '基于流程规整矩阵的流程推荐技术', '叶岩明; 尹建伟; 曹斌', '2013', '计算机集成制造系统', '876A4OG7xU1HEKWgKfd4zQ');
INSERT INTO `search_paper_title` VALUES (1345, '一种基于近距离最大子图优先的业务流程推荐技术', '曹斌; 尹建伟; 邓水光; 王东京; 徐悦甡', '2013', '计算机学报', '876A4OG7xU1HEKWgKfd4zQ');
INSERT INTO `search_paper_title` VALUES (1346, '基于Levenshtein距离的流程检索方法', '曹斌; 尹建伟; 陈慧蕊', '2012', '计算机集成制造系统', '876A4OG7xU1HEKWgKfd4zQ');
INSERT INTO `search_paper_title` VALUES (1347, '地理时空大数据协同计算技术', '骆剑承; 胡晓东; 吴炜; 王博', '2016', '地球信息科学学报', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1348, '联合概率密度空间的遥感自适应变化检测方法', '吴炜; 沈占锋; 吴田军; 王卫红', '2016', '测绘学报', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1349, '复合类别支持的多元线性回归遥感影像色彩归一化方法', '吴炜; 程熙; 顾国民', '2016', '地球信息科学学报', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1350, '一种面向遥感影像色彩归一化的多特征点约束直方图规整方法', '吴炜; 王卫红; 夏列钢; 杨海平', '2015', '中国', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1351, '多尺度的不透水面信息遥感提取方法与应用', '程熙; 吴炜; 沈占锋', '2015', '成都：西南交通大学出版社', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1352, '批量遥感影像湖泊提取后的矢量拼接策略问题', '沈占锋; 李均力; 夏列钢; 吴炜; 骆剑承', '2015', '武汉大学学报(信息科学版)', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1353, '联合概率密度脊提取的影像镶嵌色彩一致性处理方法', '吴炜; 沈占锋; 李均力; 杨海平; 骆剑承', '2013', '测绘学报', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1354, '分类线性回归的Landsat影像去云方法', '吴炜; 骆剑承; 沈占锋; 王卫红', '2013', '武汉大学学报(信息科学版)', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1355, '联合概率密度脊提取的影像镶嵌色彩一致性处理方法', '吴炜; 沈占锋; 李均力; 杨海平; 骆剑承', '2013', '测绘学报', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1356, '光谱和形状特征相结合的高分辨率遥感图像的建筑物提取方法', '吴炜; 骆剑承; 沈占锋; 朱志文', '2012', '武汉大学学报(信息科学版)', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1357, '面向遥感影像镶嵌的SVR色彩一致性处理', '吴炜; 骆剑承; 李均力; 杨海平; 沈占锋', '2012', '中国图象图形学报', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1358, '采用并行均值漂移算法实现农林地块边界的精确提取', '沈占锋; 骆剑承; 吴炜; 胡晓东', '2011', '中国图象图形学报', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1359, 'Ship recognition from high resolution remote sensing imagery aided by spatial relationship', '吴炜; 骆剑承; 乔程', '2010', 'Ship recognition from high resolution remote sensing imagery aided by spatial relationship', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1360, '一种基于飞行控制信息的无人机遥感影像自动拼接方法', '吴炜; 朱志文; 骆剑承; 沈占锋; 郜丽静; 周亚男', '2010', '中国', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1361, '复杂背景下的粉笔数字字符自动提取方法研究', '吴炜; 骆剑承; 胡晓东; 沈占锋', '2009', '计算机应用研究', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1362, '均值漂移高分辨率遥感影像多尺度分割的集群实现', '吴炜; 沈占锋; 骆剑承; 胡晓东', '2009', '计算机工程与应用', '2FftEsr9oKfTEnpg4DLtIDw');
INSERT INTO `search_paper_title` VALUES (1363, 'EasiDEF:一种水平化轻量级物联网数据交换协议', '侯陈达; 李栋; 邱杰凡; 崔莉', '2014', '计算机学报', 'tXCtpUxTTKbnGtPVbte2FPw');
INSERT INTO `search_paper_title` VALUES (1364, 'EasiSHA：一种软硬件协同的物联网可重塑终端架构设计', '石海龙; 李栋; 邱杰凡; 崔莉', '2014', '计算机研究与发展', 'tXCtpUxTTKbnGtPVbte2FPw');
INSERT INTO `search_paper_title` VALUES (1365, '一种可重塑的物联网终端', '石海龙; 李栋; 邱杰凡; 赵泽; 崔莉', '2013', '中国', 'tXCtpUxTTKbnGtPVbte2FPw');
INSERT INTO `search_paper_title` VALUES (1366, 'EasiSNP：一种基于时空属性的传感器网络编程方法', '邱杰凡; 李栋; 石海龙; 崔莉', '2013', '计算机学报', 'tXCtpUxTTKbnGtPVbte2FPw');
INSERT INTO `search_paper_title` VALUES (1367, '一种物联网计算任务调度系统及其方法', '石海龙; 李栋; 邱杰凡; 赵泽; 崔莉', '2012', '中国', 'tXCtpUxTTKbnGtPVbte2FPw');
INSERT INTO `search_paper_title` VALUES (1368, '无线传感器网络节点远程代码更新系统及方法', '邱杰凡; 李栋; 石海龙; 赵泽; 崔莉', '2012', '中国', 'tXCtpUxTTKbnGtPVbte2FPw');
INSERT INTO `search_paper_title` VALUES (1369, 'EasiCache：一种基于缓存机制的低开销传感器网络代码更新方法', '邱杰凡; 李栋; 石海龙; 杜文振', '2012', '计算机学报', 'tXCtpUxTTKbnGtPVbte2FPw');
INSERT INTO `search_paper_title` VALUES (1370, 'EasiLWR：一种轻量级传感器网络无线重编程技术', '邱杰凡; 李栋; 石海龙; 崔莉', '2011', '软件学报', 'tXCtpUxTTKbnGtPVbte2FPw');
INSERT INTO `search_paper_title` VALUES (1371, '基于相变存储器和闪存的数据库事务恢复模型', '范玉雷; 孟小峰', '2013', '计算机学报', 'tXCtpUxTTKYcQzGu4WbEsw');
INSERT INTO `search_paper_title` VALUES (1372, '基于固态硬盘内部并行的数据库表扫描与聚集', '范玉雷; 赖文豫; 孟小峰', '2012', '计算机学报', 'tXCtpUxTTKYcQzGu4WbEsw');
INSERT INTO `search_paper_title` VALUES (1373, '一种基于闪存的数据库恢复方法', '孟小峰; 向锂; 范玉雷', '2010', '中国', 'tXCtpUxTTKYcQzGu4WbEsw');
INSERT INTO `search_paper_title` VALUES (1374, '面向网络利用的移动Agent的形式化研究', '焦健; 王春平; 肖庆', '2013', '合肥工业大学学报(自然科学版)', 'k2By2BHpfOQiWJlzusrAPWwg');
INSERT INTO `search_paper_title` VALUES (1375, '基于相对决策熵的决策树算法及其在入侵检测中的应用', '江峰; 王春平; 曾惠芬', '2012', '计算机科学', 'k2By2BHpfOQiWJlzusrAPWwg');
INSERT INTO `search_paper_title` VALUES (1376, '一种面向应用层目标的网络主动防御系统', '肖庆; 焦健; 王春平', '2012', '一种面向应用层目标的网络主动防御系统', 'k2By2BHpfOQiWJlzusrAPWwg');
INSERT INTO `search_paper_title` VALUES (1377, '基于空间角度传递的多跳AOA三维定位算法研究与在地形建模上的应用', '夏明; 毛科技; 何文秀; 赵小敏; 方硕瑾; 陈庆章', '2012', '传感技术学报', 'thxMLiZ2TRan2FwFjfu4BlQ');
INSERT INTO `search_paper_title` VALUES (1378, '采用Hull树的贪婪地理位置路由算法的设计', '毛科技; 赵小敏; 衣俊艳; 夏明; 雷艳静; 王尧; 陈庆章', '2012', '传感技术学报', 'thxMLiZ2TRan2FwFjfu4BlQ');
INSERT INTO `search_paper_title` VALUES (1379, '基于能量和距离的分簇式WSN路由协议设计', '赵小敏; 毛科技; 王正莉; 陈庆章', '2012', '解放军理工大学学报(自然科学版)', 'thxMLiZ2TRan2FwFjfu4BlQ');
INSERT INTO `search_paper_title` VALUES (1380, '基于共面度和分层结构的WSN三维定位算法', '陈庆章; 毛科技; 何文秀; 赵小敏; 邵奔', '2012', '电子测量与仪器学报', 'thxMLiZ2TRan2FwFjfu4BlQ');
INSERT INTO `search_paper_title` VALUES (1381, '网络礼仪导论课程设计', '陈庆章; 毛科技; 王子仁', '2012', '计算机教育', 'thxMLiZ2TRan2FwFjfu4BlQ');
INSERT INTO `search_paper_title` VALUES (1382, 'WSN中基于区域划分的半自动DV-Hop定位算法', '毛科技; 赵小敏; 何文秀; 夏明; 王磊; 陈庆章', '2012', '计算机科学', 'thxMLiZ2TRan2FwFjfu4BlQ');
INSERT INTO `search_paper_title` VALUES (1383, '无线传感网络中基于共面度的三维定位算法研究与设计', '毛科技; 赵小敏; 邵奔; 陈庆章', '2011', '传感技术学报', 'thxMLiZ2TRan2FwFjfu4BlQ');
INSERT INTO `search_paper_title` VALUES (1384, 'PBL理论探讨及教师的角色认识', '陈庆章; 古辉; 王子仁; 梁荣华; 毛科技', '2011', '计算机教育', 'thxMLiZ2TRan2FwFjfu4BlQ');
INSERT INTO `search_paper_title` VALUES (1385, '激发学生学习动机的要素和操作方法研究', '陈庆章; 刘维超; 宦若虹; 毛科技', '2010', '教育探索', 'thxMLiZ2TRan2FwFjfu4BlQ');
INSERT INTO `search_paper_title` VALUES (1386, 'Design of a lighting system for energy saving based on wireless sensor network', '陈庆章; 赵小敏; 毛科技; 洪卫丹', '2010', '机电工程', 'thxMLiZ2TRan2FwFjfu4BlQ');
INSERT INTO `search_paper_title` VALUES (1387, '问题导向学习(PBL)及其在计算机网络课程中的实践', '陈庆章; 刘维超; 宦若虹; 毛科技', '2010', '高等农业教育', 'thxMLiZ2TRan2FwFjfu4BlQ');
INSERT INTO `search_paper_title` VALUES (1388, 'Data-Centric Routing Mechanism Using Hash-Value in Wireless Sensor Network', '毛科技; 赵小敏; 宦若虹; 蔡韶华; 陈庆章', '2010', '传感技术学报', 'thxMLiZ2TRan2FwFjfu4BlQ');
INSERT INTO `search_paper_title` VALUES (1389, 'Similitude Included Angle Theorem and Application in Graphics', '丁国正; 余世明; 周德龙', '2009', '中国图象图形学报', '8QkeIdENk48');
INSERT INTO `search_paper_title` VALUES (1390, 'Constructive Neuron Networks Classification Algorithm Based on Biomimetic Pattern Recognition', '王宪保; 周德龙; 王守觉', '2007', '计算机学报', '8QkeIdENk48');
INSERT INTO `search_paper_title` VALUES (1391, '基于拓扑流形的PCA人脸识别算法研究', '陆飞; 曹文明; 周德龙', '2005', '2005中国控制与决策学术年会', '8QkeIdENk48');
INSERT INTO `search_paper_title` VALUES (1392, '基于局部熵的小波变换图像融合算法', '周德龙; 余孟杰', '2005', '计算机仿真', '8QkeIdENk48');
INSERT INTO `search_paper_title` VALUES (1393, '基于 Gabor 变换的每类单个训练样本人脸识别研究', '庄德文; 周德龙; 王宪保', '2005', '计算机应用研究', '8QkeIdENk48');
INSERT INTO `search_paper_title` VALUES (1394, '基于网络编码的无线传感器网络瓶颈区域生存时间优化策略', '田贤忠; 阳胜', '2015', '计算机学报', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1395, '无线传感器网络应用简单Reed-Solomon编码的低能耗和低时延可靠数据收集方案', '朱艺华; 徐骥; 田贤忠; 池凯凯', '2015', '计算机学报', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1396, '无线传感器网络中结合节点传输范围和网络编码的节能策略', '田贤忠; 阳胜; 徐卫', '2015', '计算机科学', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1397, '基于二进制分子通信模型的多播可靠性确定方法', '程珍; 池凯凯; 李燕君; 朱艺华; 田贤忠', '2014', 'CN201410558844.8', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1398, '一种基于二进制分子通信模型的通信方法', '程珍; 池凯凯; 朱艺华; 李燕君; 田贤忠', '2014', 'CN201410556946.6', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1399, '基于二进制分子通信模型的单链路时延确定方法', '程珍; 池凯凯; 李燕君; 朱艺华; 田贤忠', '2014', 'CN201410557885.5', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1400, '基于二进制分子通信模型的单链路可靠性确定方法', '程珍; 池凯凯; 李燕君; 朱艺华; 田贤忠', '2014', 'CN201410557172.9', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1401, '基于二进制分子通信模型的多播时延确定方法', '程珍; 池凯凯; 李燕君; 朱艺华; 田贤忠', '2014', 'CN201410557226.1', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1402, '一种无线纳米传感器网络低冲突速率区分多址接入方法', '池凯凯; 李燕君; 田贤忠; 潘建; 朱艺华', '2013', '中国', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1403, 'IEEE802·11无线局域网低时延节能方法', '朱艺华; 栾慎吉; 池凯凯; 田贤忠; 潘建', '2013', '中国', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1404, '无线网络中任意路径编码感知机会路由', '田贤忠; 陈群; 朱金凤', '2013', '北京邮电大学学报', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1405, '无线网络编码增益感知的低时延路由协议', '田贤忠; 朱艺华; 缪得志', '2013', '电子学报', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1406, '一种基于流内与流间网络编码的无线路由算法', '田贤忠; 周前伟', '2013', '电子学报', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1407, '一种基于OOK调制的无线传感器网络中高发送能量效率源编码方法', '池凯凯; 程珍; 朱艺华; 孙立; 田贤忠', '2012', '中国', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1408, '一种基于能量的网络编码感知路由算法', '田贤忠; 缪得志; 胡同森', '2012', '小型微型计算机系统', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1409, '无线网络中基于编码感知的能量优化路由算法', '田贤忠; 朱金凤; 陈群; 胡同森', '2012', '传感技术学报', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1410, 'An Energy-saving Routing Based on Network Coding on Intersecting Flows', '朱艺华; 唐春光; 田贤忠', '2011', '电子与信息学报', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1411, 'IEEE 802.11无线网络节点的竞争窗口平均长度的数学建模方法', '朱艺华; 汤一平; 田贤忠; 李燕君', '2011', '中国', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1412, '一种基于网络编码的无线网络机会路由算法', '田贤忠; 刘强; 胡同森', '2011', '传感技术学报', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1413, '基于视觉的Web页面分块算法的改进与实现', '高乐; 张健; 田贤忠', '2009', '计算机系统应用', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1414, '基于Qt图形库Ingres空间数据库驱动的实现', '佘静涛; 田贤忠; 陈长军', '2009', '计算机系统应用', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1415, '一种改进Tiny-Sync的算法', '田贤忠; 陈长军; 裴佳佳', '2009', '计算机系统应用', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1416, '基于指数时延的无线传感器网络时钟同步估计', '田贤忠; 龚婷; 胡同森', '2009', '小型微型计算机系统', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1417, '无线传感器网络时间同步概率误差研究', '田贤忠; 陈长军; 胡同森', '2009', '计算机应用研究', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1418, '移动IP网络中基于遗传算法的多步寻呼策略及性能分析', '李楠; 潘建; 田贤忠; 朱艺华', '2008', '电子学报', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1419, '无线传感器网络按需时间同步算法研究', '田贤忠; 陈登; 胡同森', '2008', '传感技术学报', 'k2By2BHpfOQiXeT4AcRkXNEQ');
INSERT INTO `search_paper_title` VALUES (1420, 'Multi-local Search and Adaptive Niching based Memetic Algorithm with a Consensus Criterion for Data Clusteridng', 'W. Sheng; S. Chen; G. Howells; G. Xiao; 毛家发', '2014', 'IEEE Transactions on Evolutionary Computation', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1421, 'Research on steganography capacity in the DCT domain based on MCUU model', '毛家发; 黄艳红; NIU Xin-xin(钮心忻); Gang XIAO(肖刚)', '2014', '2014 3rd International Conference on Computer Science and Electronics Engineering', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1422, 'JPEG2000 Image Maximum Steganography Payload Based on MPUI Model', '毛家发; 钮心忻; 杨义先; 张娜娜; 盛伟国', '2014', '软件学报', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1423, '基于MCUU模型下的DCT域图像隐写容量评估方法', '毛家发,黄艳红,肖刚,程振波,卢书芳,胡海彪,范伟康,彭琼丽', '2013', '中国', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1424, 'Semi-Fragile Watermarking Schemes for H.264 Video', '毛家发; 杨义先', '2013', 'Steganography and Watermarking', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1425, 'Steganography and Watermarking-Multiple Watermarking Using Discrete Wavelet Transform', '毛家发; 杨义先', '2013', 'Steganography and Watermarking', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1426, 'Research of Image Watermarking Payload Estimation Based on HVS in the Spatial Domain', 'Zhang Na Na; 毛家发; Yin Jing; Yang Xiao Fan', '2013', 'International Journal of Advancements In Computing Technology', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1427, 'Research on the Watermarking Payload for Spatial-Domain Image under Transparent Conditions', 'Zhang Na-na; Yin Jing; 毛家发; Su Gui-Lian', '2012', '2012 IEEE 14th International Conference on Communication Technology', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1428, 'Research of Spatial Domain Image DigitalWatermarking Payload', '毛家发; Zhang Ru; Niu Xin-xin; Yang Yi-xian; Zhou Lin-Na', '2011', 'EURASIP Journal on Information Security', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1429, '基于JPEG净图定量描述的隐写分析方法', '毛家发; 钮心忻; 杨义先; 时书剑', '2011', '电子学报', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1430, 'A Novel General Steganalysis Technique Based on Cover Image Describing', '毛家发; 林家骏', '2010', '计算机学报', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1431, 'Statistica lModeling of DCT Coeff ic ients and Detector Performance in Terms of Rece iver Opera tion Character istic Curves', '毛家发,林家骏，韩津生', '2009', '中国图象图形学报', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1432, 'An Attacked Image Based Hidden Messages Bl ind Detect Technique', '毛家发，林家骏，戴蒙', '2009', '计算机学报', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1433, 'A Method to Estimate the Steganographic Capacity in DCT Domain Based on MCUU Model', '毛家发; 黄艳红; 钮心忻; 肖刚; 朱李楠; 盛伟国', '2009', '武汉大学学报(英文版)', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1434, 'Research on watermarking payload of the spatial images based on MPUI model', '毛家发; 黄艳红; 钮心忻; 肖刚; 盛伟国; 瞿志国', '2009', '山东大学学报(理学版)', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1435, 'A Biometric Key Generation Method based on Semi-supervised Data Clustering', 'W. Sheng; S.Y. Chen; G. Xiao; J.F. Mao(毛家发); Y.J.  Zheng', '2008', 'IEEE Transactions on Systems', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1436, 'A Theoretical 2D Image Model for Locating 3D Targets', '毛家发; Gang Xiao; Wei-Guo Sheng; Tasawar Hayat; Xiaohui Liu', '2008', 'International Journal of Computer Mathematics', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1437, 'A Steganalysis Method in the DCT domain', '毛家发; 钮心忻; Xiao Gang; Sheng Wei-Guo; ZHANG Na-Na', '2005', 'Multimedia Tools and Applications', 'BBd8X5gl31N2r8H4z2tBHw');
INSERT INTO `search_paper_title` VALUES (1506, '一种基于移动终端和增强现实技术的近距离最优公交站点导航方法', '杨旭华; 程之; 凌非; 俞佳; 王海洋', '2015', '浙江', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1507, '基于低采样率浮动车数据的全局投票地图匹配算法', '杨旭华; 汪向飞', '2015', '浙江工业大学学报', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1508, '基于重叠社团划分的大规模道路网络双层路由算法', '杨旭华; 周诗杰', '2015', '计算机科学', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1509, '一种基于重叠社团划分的大规模道路网络双层路由方法', '杨旭华; 周诗杰; 程之', '2014', '浙江', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1510, '一种基于低采样率浮动车数据的全局投票地图匹配方法', '杨旭华; 赵久强; 汪向飞', '2014', '浙江', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1511, '一种城市拥堵时段的多模式公交换乘方法', '杨旭华; 赵久强; 程之', '2014', '浙江', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1512, '基于GIS的公交网络优化系统（软件著作权:2014SR003837）', '杨旭华; 于海华', '2014', 'China', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1513, '基于K-最短路径的交通网络传输性能分析', '杨旭华; 李传告; 陈光', '2014', '浙江工业大学学报', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1514, '一个面向缺陷分析的电路成品率与可靠性的关系模型', '肖杰; 江建慧; 杨旭华; 梁家荣', '2014', '电子学报', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1515, '一种基于随机邻居节点的无标度网络攻击方法', '杨旭华; 赵久强; 彭朋; 汪向飞', '2013', '浙江', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1516, '基于GIS的最大最短路径长度的公交网络整体换乘性能优化方法', '杨旭华; 于海华; 凌非', '2013', '浙江', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1517, '一种低复杂度的网络平均路径优化方法', '杨旭华; 陈光; 彭朋', '2013', '浙江', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1518, '一种基于流量信息的交通拥堵时的公交换乘方法', '杨旭华; 周诗杰; 凌非; 张永振; 王波', '2013', '浙江', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1519, '杭州市自然科学学术成果奖一等奖：具有理想n-深度派系网络拓扑结构的公交网络模型', '杨旭华; 陈光; 陈胜勇; 王万良', '2012', '杭州市人力资源和社会保障局和杭州市科学技术协会', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1520, '浙江省高校优秀科研成果奖二等奖：具有随机重叠派系结构的复杂动态网络及其在公交网络中的应用研究', '杨旭华; 王波; 陈胜勇; 王万良', '2012', '浙江省教育厅和浙江省高等教育学会', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1521, '一种考虑近距离步行站点对的参数化公交换乘方法', '杨旭华; 张永振; 陈光', '2012', '浙江', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1522, '一种基于空间节点聚类方法的快速公交换乘方法', '杨旭华; 陈光; 赵久强; 汪向飞', '2012', '浙江', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1523, '一种基于有向随机游走的公交网络建模方法', '杨旭华; 董有郁; 周诗杰; 张永振', '2012', '浙江', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1524, '智能搜索算法在线教学实验平台的设计与实现', '徐新黎; 胡磊; 王万良; 杨旭华; 刘盛', '2012', '实验技术与管理', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1525, '一种可改善整体换乘性能的城市公共交通网络优化方法', '杨旭华; 陈光; 蒋峰岭; 孙豹; 徐新黎; 富强; 张永振; 楼顺利', '2011', '中国', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1526, '基于理想派系网络的杭州市公共交通网络优化系统软件V1.0 (软件著作权编号：2011SR029096)', '杨旭华', '2011', 'China', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1527, '城市公共交通网络数据自动搜索系统V1.0（软件著作权编号：2011SR013359）', '杨旭华', '2011', 'China', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1528, '基于随机重叠派系的可控网络直径的公交网络模型的建立方法及公交网络模型', '杨旭华; 孙豹; 蒋峰岭; 陈光', '2010', '中国', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1529, '英国研究生的互动式课堂教学探讨', '杨旭华', '2009', '中国校外教育', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1530, 'A Tentative Study in Teaching and Practice Reform of Introduction of Artificial Intelligence', '徐新黎; 王万良; 杨旭华', '2009', '计算机教育', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1531, 'An improved traffic flow-speed control design for an automated highway system', '杨旭华; 董颖颖; 杨海东; 王万良', '2009', '控制理论与应用', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1532, 'Highway traffic incident detection method based on FART neural network', '董颖颖; 杨旭华; 王万良', '2009', '机电工程', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1533, 'Research of modeling and simulation on WS and NW small-world network model', '王波; 王万良; 杨旭华', '2009', '浙江工业大学学报', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1534, 'An improved traffic flow-speed control design for an automated highway system', '杨旭华; 董颖颖; 杨海东; 王万良', '2009', '控制理论与应用', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1535, '基于FART神经网络的高速公路交通事件检测法', '董颖颖; 杨旭华; 王万良', '2009', '机电工程', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1536, 'Modeling and simulation research on WS and NW small-world network model', '王波; 王万良; 杨旭华', '2009', '浙江工业大学学报', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1537, 'An Optimal Bus Transport Transfer Algorithm Based on Weighted Complex Networks', '王波; 王万良; 杨旭华', '2008', '武汉理工大学学报(交通科学与工程版)', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1538, 'Research on Urban Public Transport Networks Based on Complex Networks', '顾前; 杨旭华; 王万良; 王波', '2008', '计算机工程', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1539, 'An Optimal Bus Transport Transfer Algorithm based on Weighted Complex Networks', '王波; 王万良; 杨旭华', '2008', '武汉理工大学学报(交通科学与工程版)', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1540, 'Research on Urban Public Transport Networks Based on Complex Networks', '顾前; 杨旭华; 王万良; 王波', '2008', '计算机工程', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1541, 'Self-learning intersection signal control system based on RBF neural network', '杨海东; 杨旭华; 王万良', '2007', '机电工程', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1542, 'A new method for the binocular reconstruction of 3D circle', '毛剑飞; 杨旭华; 张贵军', '2006', 'The 6th World Congress on Intelligent Control and Automation(WCICA 2006)(EI收录)', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1543, 'The Study of Automatic Classification for Ultrasound Placenta Images Based on Adaptive Multiple Neural Networks', '毛剑飞; 杨旭华; 田贤忠', '2006', '中国图象图形学报', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1544, 'Identification Algorithm of Expressway Steady-state Speed-density Equilibrium Relational Expression', '杨旭华; 王万良; 孙优贤', '2006', '公路交通科技', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1545, '基于Laplacian中心性的密度聚类算法', '杨旭华; 朱钦鹏; 童长飞', '2006', '计算机科学', 'aXw31wHl4Xw');
INSERT INTO `search_paper_title` VALUES (1546, '基于无线传感网的有限空间危险性气体检测装置', '邵奇可', '2013', '中国', 'gdC9pv0cs2BuARnjabVjxoA');
INSERT INTO `search_paper_title` VALUES (1547, 'Non-uniform Sampled-data Control of Networked Control Systems with Communication Constraints', '胡豪立; 邵奇可', '2013', '信息与控制', 'gdC9pv0cs2BuARnjabVjxoA');
INSERT INTO `search_paper_title` VALUES (1548, '交通网络化控制系统的控制方法', '邵奇可', '2012', '中国', 'gdC9pv0cs2BuARnjabVjxoA');
INSERT INTO `search_paper_title` VALUES (1549, 'Networked Controller Design Based on QoS', '邵奇可; 俞立; 张贵军', '2010', '自动化学报', 'gdC9pv0cs2BuARnjabVjxoA');
INSERT INTO `search_paper_title` VALUES (1550, 'Co-design Methodology for Network-based Control Systems Based on QoS', '邵奇可; 俞立; 欧林林; 张端', '2010', '自动化学报', 'gdC9pv0cs2BuARnjabVjxoA');
INSERT INTO `search_paper_title` VALUES (1551, 'Study on Software Architecture of Remote Control Systems', '邵奇可; 陈国定', '2009', '实验室研究与探索', 'gdC9pv0cs2BuARnjabVjxoA');
INSERT INTO `search_paper_title` VALUES (1552, 'Design and Applications of Networked Control Systems', '邵奇可', '2008', '控制理论与控制工程', 'gdC9pv0cs2BuARnjabVjxoA');
INSERT INTO `search_paper_title` VALUES (1553, '具有通信约束的网络化控制系统LQG控制器设计', '邵奇可; 解洋; 张江; 洑佳红', '2008', '浙江工业大学学报', 'gdC9pv0cs2BuARnjabVjxoA');
INSERT INTO `search_paper_title` VALUES (1554, '面向WSN 的自适应模糊功率控制算法研究', '邵奇可; 冯淑娜; 毛科技', '2007', '传感技术学报', 'gdC9pv0cs2BuARnjabVjxoA');
INSERT INTO `search_paper_title` VALUES (1555, 'Human motion capture data retrieval based on semantic thumbnail', '王鑫', '2015.5.1', 'Multimedia Tools and Applications', 'tXCtpUxTTKbJ2BsKUc20cHg');
INSERT INTO `search_paper_title` VALUES (1556, '人体几何建模方法综述', '王鑫', '2015.11.1', '计算机科学', 'tXCtpUxTTKbJ2BsKUc20cHg');
INSERT INTO `search_paper_title` VALUES (1557, '基于可变形运动模型的多角色语义化运动合成', '王鑫', '2015.10.1', '计算机科学', 'tXCtpUxTTKbJ2BsKUc20cHg');
INSERT INTO `search_paper_title` VALUES (1558, '一种基于滑动窗口局部匹配窗口的动作识别方法', '陈胜勇; 王其超; 沃波海; 管秋; 王鑫; 汪晓妍; 王万良', '7.CN201410432364', '浙江', 'tXCtpUxTTKbJ2BsKUc20cHg');
INSERT INTO `search_paper_title` VALUES (1559, '一种基于时间金字塔局部匹配窗口的动作识别方法', '王鑫; 汪晓妍; 沃波海; 王其超; 管秋; 陈胜勇', '9.CN201410433290', '浙江', 'tXCtpUxTTKbJ2BsKUc20cHg');
INSERT INTO `search_paper_title` VALUES (1560, '基于可变形运动模型和运动片元的多角色运动合成', '王鑫; 陈秋迪; 王万良', '2014.10.15', '计算机辅助设计与图形学学报', 'tXCtpUxTTKbJ2BsKUc20cHg');
INSERT INTO `search_paper_title` VALUES (1561, '基于流形学习的人体动作识别', '王鑫; 沃波海; 管秋; 陈胜勇', '2014.6.16', '中国图象图形学报', 'tXCtpUxTTKbJ2BsKUc20cHg');
INSERT INTO `search_paper_title` VALUES (1562, '基于可变形运动模型和运动片元的多角色运动合成', '王鑫', '2014.10.15', '计算机辅助设计与图形学学报', 'tXCtpUxTTKbJ2BsKUc20cHg');
INSERT INTO `search_paper_title` VALUES (1563, '基于粗糙度的三维模型保细节滤波', '张旭东; 方旭东; 陈佳舟; 缪永伟', '2015.12.1', '计算机辅助设计与图形学学报', 'soSs6HBtVdof7eBjVwZjEA');
INSERT INTO `search_paper_title` VALUES (1564, '提示笔刷的数字油画画布自动生成', '陈佳舟; 胡文文; 何栋; 缪永伟', '2015.6.15', '图学学报', 'soSs6HBtVdof7eBjVwZjEA');
INSERT INTO `search_paper_title` VALUES (1565, '基于交叉点分析的线条画矢量化', '陈佳舟,雷琦,缪永伟,彭群生', '2014.10.17', '第十届中国计算机图形学大会', 'soSs6HBtVdof7eBjVwZjEA');
INSERT INTO `search_paper_title` VALUES (1566, 'L0梯度极小化耦合梯度保真的保结构图像平滑', '丁志鹏, 张少雄, 陈佳舟, 彭群生, 王章野', '2014.07.18', '中国科学(F辑:信息科学)', 'soSs6HBtVdof7eBjVwZjEA');
INSERT INTO `search_paper_title` VALUES (1567, '基于虚拟模型的水稻冠层叶面积计算方法', '丁维龙; 谢涛; 徐利锋; 张义凯', '2017.1.23', '农业工程学报', 'tXCtpUxTTKY3SlJ8JQqJ6Q');
INSERT INTO `search_paper_title` VALUES (1568, 'Genetic algorithmbasedapproachtooptimizephenotypicaltraitsofvirtual rice', '徐利锋', '2016.5.11', 'Journal of Theoretical Biology', 'tXCtpUxTTKY3SlJ8JQqJ6Q');
INSERT INTO `search_paper_title` VALUES (1569, '一种基于植物功能与结构模型的作物虚拟育种方法', '徐利锋; 丁维龙; 高楠', '4.CN201510307236', 'CN201510307236.4', 'tXCtpUxTTKY3SlJ8JQqJ6Q');
INSERT INTO `search_paper_title` VALUES (1570, 'Design and Realization of Optimization System for Rice Type', '丁维龙; 徐利锋; 危扬; 高楠', '2015', '系统仿真学报', 'tXCtpUxTTKY3SlJ8JQqJ6Q');
INSERT INTO `search_paper_title` VALUES (1571, '一种结合作物虚拟生长模型的水稻株型定量控制方法', '徐利锋; 丁维龙; 危扬; 陈淑娇; 刘洋; 郑蕾; 程志君', '4.CN201410357630', 'CN201410357630.4', 'tXCtpUxTTKY3SlJ8JQqJ6Q');
INSERT INTO `search_paper_title` VALUES (1572, '一种比较不同植物形态相似度的计算机方法', '丁维龙; 吴水生; 徐利锋; 程志君; 危扬; 陈淑娇; 刘洋; 郑蕾', '5.CN201310504139', 'CN201310504139.5', 'tXCtpUxTTKY3SlJ8JQqJ6Q');
INSERT INTO `search_paper_title` VALUES (1573, 'Study and Implementation of Functional-structural Model of Rice GroIMP', '徐利锋; 危扬; 丁维龙; Gerhard Buck-Sorlin; 程志君', '2013.7', '系统仿真学报', 'tXCtpUxTTKY3SlJ8JQqJ6Q');
INSERT INTO `search_paper_title` VALUES (1574, 'Intelligent modeling method for plant morphology based on gene expression programming', '丁维龙; 胡辰; 程志君; 徐利锋', '2013', '农业工程学报', 'tXCtpUxTTKY3SlJ8JQqJ6Q');
INSERT INTO `search_paper_title` VALUES (1575, 'Visual Simulation of Plant Interacting with Raindrops', '丁维龙; 金胡俊; 徐利锋; 程志君', '2013', '小型微型计算机系统', 'tXCtpUxTTKY3SlJ8JQqJ6Q');
INSERT INTO `search_paper_title` VALUES (1576, '一种植物与雨滴实时交互过程的计算机模拟方法', '丁维龙; 金胡俊; 徐利锋; 胡辰; 吴水生; 陈淑娇', '7.CN201210043015', 'CN201210043015.7', 'tXCtpUxTTKY3SlJ8JQqJ6Q');
INSERT INTO `search_paper_title` VALUES (1577, 'Circuit Reliability Estimation Based on an Iterative PTM Model with Hybrid Coding', '肖杰', '2016.6.1', 'Microelectronics Journal', 'tXCtpUxTTKbOZWCaXlkVmA');
INSERT INTO `search_paper_title` VALUES (1578, '一个面向缺陷分析的电路成品率与可靠性的关系模型', '肖杰; 江建慧; 杨旭华; 梁家荣', '2014.04.01', '电子学报', 'tXCtpUxTTKbOZWCaXlkVmA');
INSERT INTO `search_paper_title` VALUES (1579, '一种基于迭代PTM模型的电路可靠性评估方法', '肖杰; 江建慧; 朱旭光', '2014.07.01', '计算机学报', 'tXCtpUxTTKbOZWCaXlkVmA');
INSERT INTO `search_paper_title` VALUES (1580, '面向晶体管级广义门电路的PTM可靠性计算方法', '肖杰; 江建慧; 梁家荣', '2014.10.01', '中国科学F辑:信息科学', 'tXCtpUxTTKbOZWCaXlkVmA');
INSERT INTO `search_paper_title` VALUES (1581, '结合版图结构信息的门级电路可靠性评估方法的研究', '肖杰', '2013.03.18', '计算机系统结构', 'tXCtpUxTTKbOZWCaXlkVmA');
INSERT INTO `search_paper_title` VALUES (1582, '面向缺陷分析的广义门电路故障概率的计算', '肖杰; 江建慧', '2013.04.01', '计算机辅助设计与图形学学报', 'tXCtpUxTTKbOZWCaXlkVmA');
INSERT INTO `search_paper_title` VALUES (1583, '考虑时间因素的不同基本门故障概率计算', '肖杰; 江建慧', '2013.04.01', '电子学报', 'tXCtpUxTTKbOZWCaXlkVmA');
INSERT INTO `search_paper_title` VALUES (1584, 'ARM程序执行周期估计的基于模拟的非线性方法', '孔亮亮; 江建慧; 肖杰; 蒋园园', '2012.2.1', '计算机研究与发展', 'tXCtpUxTTKbOZWCaXlkVmA');
INSERT INTO `search_paper_title` VALUES (1585, '结合版图结构信息的基本门电路故障概率估计', '肖杰; 江建慧', '2012.02.01', '电子学报', 'tXCtpUxTTKbOZWCaXlkVmA');
INSERT INTO `search_paper_title` VALUES (1586, '一种阴影区域的可通行性检测方法', '高华; 赵春霞; 张浩峰', '2013.11.15', '计算机研究与发展', 'kcqLkl7bTggGCJNcVxcOIA');
INSERT INTO `search_paper_title` VALUES (1587, 'Visual featuresfusion for scene images classification', '高华; 赵春霞; 张浩峰', '春季2012', 'Lecture Notes in Engineering and Computer Science', 'kcqLkl7bTggGCJNcVxcOIA');
INSERT INTO `search_paper_title` VALUES (1588, 'Cascadetraversability detection based on visual feature fusion', '高华; 赵春霞; 张浩峰', '冬季2012', 'ICIC Express Letters', 'kcqLkl7bTggGCJNcVxcOIA');
INSERT INTO `search_paper_title` VALUES (1589, 'A traversabilitydetection method based on combining One-Class SVM', '高华; 赵春霞; 张浩峰', '冬季2012', 'Journal of Information and Computational Science', 'kcqLkl7bTggGCJNcVxcOIA');
INSERT INTO `search_paper_title` VALUES (1590, '基于One-Class SVM与融合多可视化特征的可通行区域检测', '高华; 赵春霞; 韩光', '2011.11.15', '机器人', 'kcqLkl7bTggGCJNcVxcOIA');
INSERT INTO `search_paper_title` VALUES (1591, '基于最佳缝合线的序列遥感图像拼接融合方法', '秦绪佳; 王琪; 王慧玲; 郑红波; 陈胜男', '2015.10.15', '计算机科学', 'tXCtpUxTTKa1S3Tu9GOs4g');
INSERT INTO `search_paper_title` VALUES (1592, '局部更新的分层B样条医学图像非刚性配准算法', '秦绪佳; 肖佳吉; 陈珊; 王琪; 陈胜男', '小型微型计算机系统', '小型微型计算机系统', 'tXCtpUxTTKa1S3Tu9GOs4g');
INSERT INTO `search_paper_title` VALUES (1593, '邻域自适应暗原色先验的单幅图像快速去雾算法', '秦绪佳; 葛春霞; 范颖琳; 郑红波; 陈胜男', '小型微型计算机系统', '小型微型计算机系统', 'tXCtpUxTTKa1S3Tu9GOs4g');
INSERT INTO `search_paper_title` VALUES (1594, '基于法向量直方图特征描述的点云ICP拼接', '秦绪佳; 徐菲; 王建奇; 郑红波; 陈胜男', '小型微型计算机系统', '小型微型计算机系统', 'tXCtpUxTTKa1S3Tu9GOs4g');
INSERT INTO `search_paper_title` VALUES (1595, '改进的遥感图像SURF特征匹配算法', '秦绪佳; 洪夏阳; 王慧玲; 郑红波; 陈胜男', '小型微型计算机系统', '小型微型计算机系统', 'tXCtpUxTTKa1S3Tu9GOs4g');
INSERT INTO `search_paper_title` VALUES (1596, 'Image Enhancement Algorithm Based on Retinex of Trilateral Filter in HSV Color Space', '秦绪佳; 程燕飞; 范颖琳; 郑红波; 陈胜男', '小型微型计算机系统', '小型微型计算机系统', 'tXCtpUxTTKa1S3Tu9GOs4g');
INSERT INTO `search_paper_title` VALUES (1597, '移动设备眼动跟踪技术', '程时伟; 陆煜华; 蔡红刚', '2016.5', '浙江大学学报(工学版)', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1598, '面向多设备交互的眼动跟踪方法', '程时伟; 孙志强; 陆煜华', '2016.7.15', '计算机辅助设计与图形学学报', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1599, '移动设备眼动跟踪技术', '程时伟; 陆煜华; 蔡红刚', '2016.5', '浙江大学学报(工学版)', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1600, '基于眼动跟踪的移动设备视频智能播放系统（2015SR017618 软件著作权）', '程时伟', '2015.1.1', 'China', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1601, '面向移动眼动跟踪的图片浏览系统（2015SR017621 软件著作权）', '程时伟', '2015.1.1', 'China', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1602, '分布式眼动跟踪系统(2015SR125294 软件著作权)', '程时伟', '2015.7.1', 'China', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1603, '产品设计中的开放式群体协作创新模式实验', '孙艳; 刘肖健; 王万良; 计时鸣; 程时伟; 吴剑锋', '2015', '计算机集成制造系统', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1604, '产品设计中的开放式群体协作创新模式实验', '孙艳; 刘肖健; 王万良; 计时鸣; 程时伟; 吴剑锋', '2014.10', '计算机集成制造系统', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1605, 'Killer UX Design', '程时伟', '2014.2.1', '人民邮电出版社', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1606, '基于眼动数据可视化的阅读辅助系统（2014SR023268）', '程时伟', '2014.2.26', 'China', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1607, '基于众包的眼动数据记录系统（2014SR023267）', '程时伟', '2014.2.26', 'China', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1608, '用于移动设备人机交互的眼动跟踪方法', '程时伟; 孙志强', '2014.8.15', '计算机辅助设计与图形学学报', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1609, '眼动数据可视化综述', '程时伟; 孙凌云', '2014.5.15', '计算机辅助设计与图形学学报', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1610, 'EMD与小波分析结合的特征保持图像去噪方法', '王卫红; 程时伟; 张素琼; 秦绪佳', '2013.10.15', '计算机科学', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1611, 'EMD与小波分析结合的特征保持图像去噪方法', '王卫红; 程时伟; 张素琼; 秦绪佳', '2013.10.15', '计算机科学', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1612, '产品基因调控网络模型及其对设计过程的辅助', '刘肖健; 孙艳; 吴剑锋; 程时伟', '2013.7.15', '计算机集成制造系统', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1613, 'Activity driven industrial design E-service system in cloud manufacturing', '程时伟; 刘肖健', '2012.7.15', '计算机集成制造系统', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1614, '改进的规范化卷积图像修复算法', '秦绪佳; 桑贤生; 程时伟; 徐晓刚', '2011.2.15', '计算机辅助设计与图形学学报', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1615, '优化社交行为的手机通讯录自适应用户界面设计', '程时伟; 童琪杰; 杨东伟', '2011.9.17', '第七届和谐人机环境联合学术会议（HHME2011)、第20届全国多媒体学术会议（NCMT2011）、第7届全国人机交互学术会议（CHCI2011）、第7届全国普适计算学术会议（PCC2011）', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1616, '一种通讯录自适应显示方法及其终端', '程时伟; 秦绪佳; 杨东伟; 童琪杰', 'X.ZL201110261858', '中国', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1617, 'An improved image inpainting algorithm based on normalized convolution', '秦绪佳; 桑贤生; 程时伟; 徐晓刚', '2011.2.1', 'Jisuanji Fuzhu Sheji Yu Tuxingxue Xuebao/Journal of Computer-Aided Design and Computer Graphics', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1618, 'Research on Interaction Design of Information Visualization and Its Application Example', '程时伟; 罗玉容', '2011.4.20', '创意与设计', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1619, 'Context Awareness Driven Adaptive Mobile User Interface Model', '程时伟; 刘肖健; 孙守迁', '2010.7.16', '中国图象图形学报', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1620, 'An Approach to Usability Evaluation for Mobile Computing User Interface Based on Eye-tracking', '程时伟; 石元伍; 孙守迁', '2009.4.15', '电子学报', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1621, 'Rough Sets Method of Rule Reasoning for Adaptive Human-Computer Interface', '程时伟; 孙守迁; 柴春雷', '2008', '计算机辅助设计与图形学学报', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1622, 'Human-computer interaction resource model based on distributed cognition', '程时伟; 孙守迁', '2008', '计算机集成制造系统', '3T5YSmeI6Io');
INSERT INTO `search_paper_title` VALUES (1623, '在复杂场景中单个人脸的实时跟踪方法', '寇超; 白琮; 陈泉林; 王华红; 王少波', '2008102003102', '中国', '2FftEsr9oKfR6zZzYBYAdMw');
INSERT INTO `search_paper_title` VALUES (1624, '在彩色视频图像中提取车辆的方法', '白琮; 寇超; 陈泉林; 洪亮; 李继豪', '200810200309X', '中国', '2FftEsr9oKfR6zZzYBYAdMw');
INSERT INTO `search_paper_title` VALUES (1625, '传感器网络中语义事件区域查询处理', '李英龙; 朱艺华; 吕明琪', '2017.5.15', '计算机研究与发展', 'tXCtpUxTTKaPyGY872BwhEg');
INSERT INTO `search_paper_title` VALUES (1626, '无源感知网络中采用动态分片的IPv6数据包传递方案', '邱树伟; 李英龙; 袁利永', '2017.7.15', '计算机工程', 'tXCtpUxTTKaPyGY872BwhEg');
INSERT INTO `search_paper_title` VALUES (1627, '多无线传感器网络中连接查询处理', '莫尚丰; 范永健; 王晓亮; 余庆春; 李英龙', '2016.4.8', '系统仿真学报', 'tXCtpUxTTKaPyGY872BwhEg');
INSERT INTO `search_paper_title` VALUES (1628, '一种基于传感器网络事件检测的kNN查询方法', '陈红; 李英龙; 朱建祥', '0.201410125872', '1.4.2014', 'tXCtpUxTTKaPyGY872BwhEg');
INSERT INTO `search_paper_title` VALUES (1629, '无线传感器网络中的top-k连接查询处理', '莫尚丰; 陈丁洁; 陈红; 李英龙; 李翠平', '2013.3.1', '计算机学报', 'tXCtpUxTTKaPyGY872BwhEg');
INSERT INTO `search_paper_title` VALUES (1630, '实时响应物联网中基于查询的数据转发方案', '李英龙; 陈红; 莫尚丰', 'March2012', '计算机学报', 'tXCtpUxTTKaPyGY872BwhEg');
INSERT INTO `search_paper_title` VALUES (1631, '改进的加权C-F模型方法在煤矿安全评估中的应用', '李英龙; 莫尚丰; 周志强', '2011.1.1', '中国安全科学学报', 'tXCtpUxTTKaPyGY872BwhEg');
INSERT INTO `search_paper_title` VALUES (1632, '基于集合最大流算法的WSN栅栏修复方法研究', '戴光麟; 方凯; 方飞; 戴国勇; 夏明; 宦若虹; 毛科技', '2016.12', '传感技术学报', 'Ya6kZsyQ1k1FcTyF4l8dcg');
INSERT INTO `search_paper_title` VALUES (1633, '浓雾环境下车车通信对交通事故的影响分析', '陈宇峰; 向郑涛; 闫蓬; 董亚波; 夏明', '2016.8.15', '交通运输系统工程与信息', 'Ya6kZsyQ1k1FcTyF4l8dcg');
INSERT INTO `search_paper_title` VALUES (1634, '一种分布式的1-栅栏覆盖构建算法', '应可珍; 邬锦彬; 夏明; 雷艳静; 肖致友; 陈庆章', '2016.3.15', '电子与信息学报', 'Ya6kZsyQ1k1FcTyF4l8dcg');
INSERT INTO `search_paper_title` VALUES (1635, '面向非视距环境的室内定位算法', '毛科技; 邬锦彬; 金洪波; 苗春雨; 夏明; 陈庆章', '2016.5.15', '电子学报', 'Ya6kZsyQ1k1FcTyF4l8dcg');
INSERT INTO `search_paper_title` VALUES (1636, '车联网建模和统计性质分析及其路由策略综述', '陈宇峰; 向郑涛; 董亚波; 夏明', '2015.12.10', '计算机应用', 'Ya6kZsyQ1k1FcTyF4l8dcg');
INSERT INTO `search_paper_title` VALUES (1637, '采用分层结构的WSN室内三维定位算法的研究和设计', '毛科技; 戴光麟; 夏明; 邵奔; 陈庆章', '2013', 'pp 277-280', 'Ya6kZsyQ1k1FcTyF4l8dcg');
INSERT INTO `search_paper_title` VALUES (1638, '采用Hull树的贪婪地理位置路由算法的设计', '毛科技; 赵小敏; 衣俊艳; 夏明; 雷艳静; 王尧; 陈庆章', '2012', 'Chinese Journal of Sensors and Actuators', 'Ya6kZsyQ1k1FcTyF4l8dcg');
INSERT INTO `search_paper_title` VALUES (1639, '基于空间角度传递的多跳AOA三维定位算法研究与在地形建模上的应用', '夏明; 毛科技; 何文秀; 赵小敏; 方硕瑾; 陈庆章', '2012', 'Chinese Journal of Sensors and Actuators', 'Ya6kZsyQ1k1FcTyF4l8dcg');
INSERT INTO `search_paper_title` VALUES (1640, 'WSN中基于区域划分的半自动DV-Hop定位算法', '毛科技; 赵小敏; 何文秀; 夏明; 王磊; 陈庆章', '2012', '计算机科学', 'Ya6kZsyQ1k1FcTyF4l8dcg');
INSERT INTO `search_paper_title` VALUES (1641, '无线传感器网络中分布式信标节点漂移检测方法', '夏明; 陈庆章; 金言; 黄昊程', '1.CN201210560187', '20.12.2012', 'Ya6kZsyQ1k1FcTyF4l8dcg');
INSERT INTO `search_paper_title` VALUES (1642, 'WSN中信标节点移动情况下的定位方法研究', '何文秀; 夏明; 赵小敏; 程荣; 陈庆章', '2011', '小型微型计算机系统', 'Ya6kZsyQ1k1FcTyF4l8dcg');
INSERT INTO `search_paper_title` VALUES (1643, 'A Novel Registrationand De-noising Method for Multiple Sequence MRI of Atherosclerosis', 'Li Junwei; 张剑华; Wang Xiaoyan; Gai Cheng; Zhang Bingyu; Guan Qiu; Chen Shengyong', '2015.8.8', '\"  2015Proceeding of the IEEE International Conference on Information and Automation', 'tXCtpUxTTKbsPbQHcdg7cg');
INSERT INTO `search_paper_title` VALUES (1644, 'Missile Vision Guidance Based-OnAdaptive Image Filtering', 'Gao Qiang; Zou Yijie; 张剑华; Liu Sheng; Xie Zhen; Chen Shengyong', '2015.8.8', '\"  2015Proceeding of the IEEE International Conference on Information and Automation', 'tXCtpUxTTKbsPbQHcdg7cg');
INSERT INTO `search_paper_title` VALUES (1645, 'Aerial Sequential Frame Decimation for Scene Reconstruction', 'Xie Zhen; Wan Fuhua; Bu Qing; Zhou Xiaolong; 张剑华; Chen Shengyong', '2015.8.8', '\"  2015 IEEE International Conference on Information and Automation', 'tXCtpUxTTKbsPbQHcdg7cg');
INSERT INTO `search_paper_title` VALUES (1646, '一种基于多序列医学图像的血管配准方法', '汪晓妍; 李军伟; 黄晓洁; 张剑华; 滕忠照; 陈胜勇', '2.CN201510088135', '浙江', 'tXCtpUxTTKbsPbQHcdg7cg');
INSERT INTO `search_paper_title` VALUES (1647, '基于前景和背景先验的多模态区域一致性的显著性对象检测方法', '张剑华; 王其超; 谢榛; 赵妍珠; 陈胜勇; 张建伟', '2.CN201510072313', '浙江', 'tXCtpUxTTKbsPbQHcdg7cg');
INSERT INTO `search_paper_title` VALUES (1648, '一种基于多特征学习的动脉粥样硬化斑块成分分割方法', '汪晓妍; 李军伟; 黄晓洁; 张剑华; 滕忠照; 陈胜勇', '1.CN201510170489', '浙江', 'tXCtpUxTTKbsPbQHcdg7cg');
INSERT INTO `search_paper_title` VALUES (1649, '基于形状先验和相似性约束的颈动脉内外壁自动分割方法', '张剑华; 何俊丽; 陈磊; 汪晓妍; 滕忠照; 管秋; 陈胜勇', '3.CN201510088158', '浙江', 'tXCtpUxTTKbsPbQHcdg7cg');
INSERT INTO `search_paper_title` VALUES (1650, 'Medical image quality assessment based on structural saliency', '张剑华; 张自然; 汪晓妍; 管秋', '2015', '浙江工业大学学报', 'tXCtpUxTTKbsPbQHcdg7cg');
INSERT INTO `search_paper_title` VALUES (1651, 'Real-time Dynamic Addressing for Spacecraft Soft Landing in the Lunar Surface', 'He Liang; Ren Qinhu; Feng Yujian; 张剑华; Liu Sheng; Chen Shengyong', '2015.8.8', '\"  2015 Proceeding of the IEEE International Conference on Information and Automation', 'tXCtpUxTTKbsPbQHcdg7cg');
INSERT INTO `search_paper_title` VALUES (1652, 'Landmark Selection andMatching for Aiding Lunar Surface Navigation', 'Feng Yujian; 张剑华; Ren Qinhu; Xie Zhen; Liu Sheng; Chen Shengyong', '2015.8.8', '\"  2015 IEEE International Conference on Information and Automation', 'tXCtpUxTTKbsPbQHcdg7cg');
INSERT INTO `search_paper_title` VALUES (1653, 'General Simulation Platformfor Vision Based UAV Testing', 'Bu Qing; Wan Fuhua; Xie Zhen; Ren Qinhu; 张剑华; Liu Sheng', '2015.8.8', 'The IEEE International Conference on Information and Automation 2015', 'tXCtpUxTTKbsPbQHcdg7cg');
INSERT INTO `search_paper_title` VALUES (1654, 'Image quality assessment based on structural saliency', '张剑华', '2014.8.20', '19th International Conference on Digital Signal Processing (DSP 2014)', 'tXCtpUxTTKbsPbQHcdg7cg');
INSERT INTO `search_paper_title` VALUES (1655, 'Compounding Local Invariant Features and Global Deformable Geometry for Medical Image Registration', '张剑华; 陈磊; 汪晓妍; 腾忠照; Adam J. Brown; Jonathan H. Gillard; 管秋; 陈胜勇', '2014.8.28', 'PLos One', 'tXCtpUxTTKbsPbQHcdg7cg');
INSERT INTO `search_paper_title` VALUES (1656, 'Active Detection and Correction of Shape Distortions Based on Moment Invariants for Active Shape Models', '张剑华; 陈胜勇; 刘盛; 管秋', '2009.9.15', '中国图象图形学报', 'tXCtpUxTTKbsPbQHcdg7cg');
INSERT INTO `search_paper_title` VALUES (1657, '有遮挡人脸识别综述：从子空间回归到深度学习', '李小薪', '2018', '计算机学报', 'BBd8X5gl31NWGcwDWDwUCQ');
INSERT INTO `search_paper_title` VALUES (1658, '基于结构感知的人脸遮挡检测方法', '李小薪; 李晶晶; 梁荣华; 冯远静; 刘义鹏', '5.CN201610028275', '浙江', 'BBd8X5gl31NWGcwDWDwUCQ');
INSERT INTO `search_paper_title` VALUES (1659, '基于贝叶斯多元分布特征提取的三维人脸识别方法', '梁荣华; 沈闻佳; 李小薪; 王海霞; 蒋莉; 胡顺福', '8.CN201510069223', '浙江', 'BBd8X5gl31NWGcwDWDwUCQ');
INSERT INTO `search_paper_title` VALUES (1660, '一种用于复杂纤维束精确重构的多级调整混合加权稀疏成像方法', '冯远静; 詹佳雯; 吴烨; 周思琪; 龚一隆; 毛文涛; 周侠; 叶峰; 梁朝凯; 李小薪; 梁荣华', '0.CN201510298776', '浙江', 'BBd8X5gl31NWGcwDWDwUCQ');
INSERT INTO `search_paper_title` VALUES (1661, '一种用于早期帕金森症预测的综合分析方法', '詹佳雯; 冯远静; 吴烨; 周思琪; 龚一隆; 毛文涛; 周侠; 叶峰; 梁朝凯; 李小薪; 梁荣华', '4.CN201510298754', '浙江', 'BBd8X5gl31NWGcwDWDwUCQ');
INSERT INTO `search_paper_title` VALUES (1662, '基于混合误差编码的人脸识别方法', '李小薪; 梁荣华; 冯远静; 蒋莉', '7.CN201510257647', '浙江', 'BBd8X5gl31NWGcwDWDwUCQ');
INSERT INTO `search_paper_title` VALUES (1663, '一种人脑组织高维可视化方法', '毛文涛; 冯远静; 吴烨; 周侠; 詹佳雯; 周思琪; 龚一隆; 叶峰; 梁朝凯; 李小薪; 梁荣华', '5.CN201510298752', '浙江', 'BBd8X5gl31NWGcwDWDwUCQ');
INSERT INTO `search_paper_title` VALUES (1664, '基于结构化误差编码的人脸遮挡检测方法', '李小薪; 戴道清', '24.10.2012', '2012.10.24', 'BBd8X5gl31NWGcwDWDwUCQ');

SET FOREIGN_KEY_CHECKS = 1;
