# Generated by Django 2.0.4 on 2018-05-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_detail',
            name='key_words',
            field=models.CharField(max_length=300),
        ),
    ]
