# Generated by Django 2.0.4 on 2018-04-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='avatar_src',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='authors',
            name='edu_experience',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='authors',
            name='work_experience',
            field=models.CharField(max_length=250),
        ),
    ]
