# Generated by Django 2.0.4 on 2018-04-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authors555',
        ),
    ]
