# Generated by Django 2.0.4 on 2018-05-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_auto_20180514_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_detail',
            name='authors',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paper_title',
            name='authors',
            field=models.CharField(max_length=200),
        ),
    ]
