# Generated by Django 2.0.4 on 2018-05-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0005_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('introduction', models.CharField(max_length=500)),
            ],
        ),
    ]
